In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import json
import warnings
warnings.filterwarnings('ignore')

# 1- Load all 8 files

1-1 six csv files

In [2]:
courses=pd.read_csv(r'student_edu_info\courses.csv')
groups=pd.read_csv(r"student_edu_info\groups.csv")
students=pd.read_csv(r"student_edu_info\students.csv")
cp=pd.read_csv(r"student_edu_info\concepts_performance.csv")
eng=pd.read_csv(r"student_edu_info\engagement_events.csv")
subs=pd.read_csv(r"student_edu_info\assignment_submissions.csv")

In [3]:
print(f"courses       : {courses.shape}")
print(f"groups        : {groups.shape}")
print(f"students      : {students.shape}")
print(f"concepts_perf : {cp.shape}")
print(f"engagement    : {eng.shape}")
print(f"submissions   : {subs.shape}")

courses       : (7, 8)
groups        : (12, 7)
students      : (502, 8)
concepts_perf : (12008, 10)
engagement    : (30866, 6)
submissions   : (1504, 9)

1-2 Json flatten nested grades

In [4]:
with open(r'student_edu_info\grades.json') as f:
    grades_raw=json.load(f)

rows=[]
for row in grades_raw:
    sid=row.get('student_id')
    cid=row.get('course_id')
    gid=row.get('group_id')
    for g in row.get('grades',[]):
        g['student_id']=sid
        g['course_id']=cid
        g['group_id']=gid

        rows.append(g)

grades=pd.DataFrame(rows)
print(f'\ngrades : {grades.shape}')

grades : (5502, 10)

1-3 Excel stack all 6 monthly sheets

In [5]:
# as the sheets attend column is different we will standraize the column
status_map={
    # sheet 2025-12
    'attended'  : 'attended',
    'Atttended' : 'attended',   
    'absent'    : 'absent',

    # sheet 2026 01
    'Present'   : 'attended',
    'Absent'    : 'absent',   

    # sheet 2026-02
    1    : 'attended',
    0    : 'absent',
    True : 'attended',
    False: 'absent',

    # sheet 2026-03
    'P'      : 'attended',
    'A'      : 'absent',

   # sheet 2026-04
    'yes'       : 'attended',
    'no'        : 'absent',
    # sheet 2026-05
    'True'      : 'attended',
    'False'     : 'absent',
}
DATETIME_COL_ALIASES=['session_datetime','datetime']
monthly_frames = []
xl = pd.ExcelFile(r'student_edu_info\attendance.xlsx')

for sheet in xl.sheet_names:
    df = pd.read_excel(r'student_edu_info\attendance.xlsx', sheet_name=sheet)

    # normalize datetime column name
    for alias in DATETIME_COL_ALIASES:
        if alias in df.columns and alias != 'session_datetime':
            df = df.rename(columns={alias: 'session_datetime'})

    # normalize status
    df['status'] = df['status'].map(status_map)
    df['month']  = str(sheet)
    
    monthly_frames.append(df)

attendance = pd.concat(monthly_frames, ignore_index=True)

print(f"attendance (all sheets): {attendance.shape}")
print(f"status unique after reconcile: {attendance['status'].unique()}")

attendance (all sheets): (13010, 7)
status unique after reconcile: <ArrowStringArray>
['attended', 'absent']
Length: 2, dtype: str

# 2- Clean & Recouncile

In [6]:
# Cleaning log to collect all issues we solve in the notebook 
clean_log=[]
def log(issue_no,file,description,action,count=None):
    clean_log.append({
        'issue':issue_no,
        'file':file,
        'description':description,
        'action':action,
        'count':count
    })
    print(f"[#{issue_no:02d}] {file} — {description} → {action}" + (f" ({count})" if count else ""))

####  first file groups.csv

In [7]:
print(groups.columns)
print(groups.shape)
print(groups.isna().sum())
print(groups.duplicated().sum())

Index(['group_id', 'group_name', 'course_id', 'stated_num_students',
       'session_day', 'session_time', 'instructor'],
      dtype='str')
(12, 7)
group_id               0
group_name             0
course_id              0
stated_num_students    0
session_day            0
session_time           0
instructor             1
dtype: int64
1

In [8]:
# issue 1 duplicated group row
dup_mask=groups.duplicated(subset='group_id',keep='first')# we wills subset the id to make sure that there is no duplicates in id
log(1,'groups.csv','duplicaed row for G01','keep first occurrence , drop duplicate',int(dup_mask.sum()))
groups=groups[~dup_mask].reset_index(drop=True)

[#01] groups.csv — duplicaed row for G01 → keep first occurrence , drop duplicate (1)

In [9]:
# issue 2 there is nan in instructor column and the row is just for test
log(2,'group.csv','G99 test_group_delete -  unreal test group ','drop row entirely',1)
groups=groups[groups['group_id']!='G99'].reset_index(drop=True)

[#02] group.csv — G99 test_group_delete -  unreal test group  → drop row entirely (1)

In [10]:
# issue 3 - missing instructor for g99 already dropped but log it
log(3, 'groups.csv', 'null instructor for G99', 'resolved by dropping G99 (issue #2)', 1)

[#03] groups.csv — null instructor for G99 → resolved by dropping G99 (issue #2) (1)

In [11]:
# issue 4 inconsistent session time formates 
def normalise_time(t):
    t = str(t).strip()
    if t in ['0', '0.0', '00:00']: return '00:00'
    if 'PM' in t.upper() or 'AM' in t.upper():
        try:
            import re
            t_clean = re.sub(r'[^0-9APMapm: ]','', t).strip()
            return pd.to_datetime(t_clean, format='%I %p').strftime('%H:%M')
        except: return t
    if len(t) == 4 and t.isdigit():
        return f"{t[:2]}:{t[2:]}"
    return t

groups['session_time'] = groups['session_time'].apply(normalise_time)
log(4, 'groups.csv', 'inconsistent session_time formats (16:00 / 6 PM / 1800)', 'normalised all to HH:MM', None)

[#04] groups.csv — inconsistent session_time formats (16:00 / 6 PM / 1800) → normalised all to HH:MM

####  second file students.csv

In [12]:
print(students.columns)
print(students.shape)
print(students.isna().sum())
print(students.duplicated().sum())

Index(['student_id', 'full_name', 'age', 'gender', 'city', 'email', 'group_id',
       'enrollment_date'],
      dtype='str')
(502, 8)
student_id         0
full_name          4
age                0
gender             0
city               0
email              0
group_id           0
enrollment_date    0
dtype: int64
0

In [13]:
# issue 5  4 null full_name values
log(5,'student.csv','4 null full_name values', 'Impute as "Unknown Student"', 4)
students['full_name'] = students['full_name'].fillna('Unknown Student')

[#05] student.csv — 4 null full_name values → Impute as "Unknown Student" (4)

In [14]:
px.box(students,x='age')

In [15]:
# issue 6 unlogical ages
age_outliers = students[(students['age'] < 16) | (students['age'] > 70)]
log(6, 'students.csv', f'Impossible ages: {age_outliers["age"].tolist()} for IDs {age_outliers["student_id"].tolist()}', 'Replace with NaN, then fill with median age', len(age_outliers))
median_age = int(students[(students['age'] >= 16) & (students['age'] <= 70)]['age'].median())
students.loc[(students['age'] < 16) | (students['age'] > 70), 'age'] = median_age

[#06] students.csv — Impossible ages: [4, -22, -5, 121, 99, 88] for IDs ['S0023', 'S0209', 'S0453', 'S0478', 'S0362', 'S0074'] → Replace with NaN, then fill with median age (6)

In [16]:
# issue 7 invalid email
log(7, 'students.csv', 'S0062 has email = "not-an-email" (no @ sign)', 'Replace with NaN — cannot infer correct email', 1)
students.loc[~students['email'].str.contains('@', na=False), 'email'] = np.nan

[#07] students.csv — S0062 has email = "not-an-email" (no @ sign) → Replace with NaN — cannot infer correct email (1)

In [17]:
# issue 8 duplicate student ids we don't trust normal duplicated 🙃
dup_students = students[students['student_id'].duplicated(keep=False)]
log(8, 'students.csv', f'duplicate student_ids: {dup_students["student_id"].unique().tolist()}', 'Keep last row (appended duplicates are at bottom — same data)', 2)
students = students.drop_duplicates(subset='student_id', keep='last').reset_index(drop=True)

[#08] students.csv — duplicate student_ids: ['S0074', 'S0362'] → Keep last row (appended duplicates are at bottom — same data) (2)

In [18]:
# issue 9 invalid group_ids GZZ, G77 not in groups.csv
valid_gids = set(groups['group_id'])
bad_gid = students[~students['group_id'].isin(valid_gids)]
log(9, 'students.csv', f'students with non-existent group_id: {bad_gid["student_id"].tolist()} → {bad_gid["group_id"].tolist()}', 'Replace group_id with NaN — cannot assign to unknown group', len(bad_gid))
students.loc[~students['group_id'].isin(valid_gids), 'group_id'] = np.nan

[#09] students.csv — students with non-existent group_id: ['S0014', 'S0095', 'S0323'] → ['GZZ', 'G77', 'G77'] → Replace group_id with NaN — cannot assign to unknown group (3)

In [19]:
# issue 10 inconsistent gender encoding (Male/MALE/M/m/male + Female/F/f/Fem/female)
def normalise_gender(g):
    g = str(g).strip().lower()
    if g in ['male', 'm']: return 'Male'
    if g in ['female', 'f', 'fem']: return 'Female'
    return np.nan
 
students['gender'] = students['gender'].apply(normalise_gender)
log(10, 'students.csv', 'gender has 10 unique encodings (Male/MALE/M/m/male + Female variants)', 'normalised all to Male/Female', None)

[#10] students.csv — gender has 10 unique encodings (Male/MALE/M/m/male + Female variants) → normalised all to Male/Female

In [20]:
# issue 11  enrollment_date stored as string not datetime
students['enrollment_date'] = pd.to_datetime(students['enrollment_date'], errors='coerce')
log(11, 'students.csv', 'enrollment_date stored as object/string', 'converted to datetime64', None)

[#11] students.csv — enrollment_date stored as object/string → converted to datetime64

#### 3 grades.jason

In [21]:
print(grades.columns)
print(grades.shape)
print(grades.isna().sum())
print(grades.duplicated().sum())

Index(['grade_id', 'assessment_id', 'assessment_title', 'type', 'score',
       'max_score', 'date', 'student_id', 'course_id', 'group_id'],
      dtype='str')
(5502, 10)
grade_id            0
assessment_id       0
assessment_title    0
type                0
score               2
max_score           0
date                0
student_id          0
course_id           0
group_id            0
dtype: int64
0

In [22]:
# issue 12  2 null score values
log(12, 'grades.json', '2 null score values', 'drop rows — cannot impute a grade without the source', 2)
grades = grades.dropna(subset=['score']).reset_index(drop=True)

[#12] grades.json — 2 null score values → drop rows — cannot impute a grade without the source (2)

In [23]:
# issue 13 inconsistence score > 100 score = 187
impossible_high = grades[grades['score'] > grades['max_score']]
log(13, 'grades.json', f'score > max_score: {impossible_high[["student_id","assessment_id","score","max_score"]].values.tolist()}', 'cap score at max_score', len(impossible_high))
grades['score'] = grades.apply(lambda r: min(r['score'], r['max_score']), axis=1)

[#13] grades.json — score > max_score: [['S0002', 'C004-QZ', 187.0, 100], ['S0005', 'C001-QZ', 78.2, 10]] → cap score at max_score (2)

In [24]:
# issue 14  score < 0 score = -10
impossible_low = grades[grades['score'] < 0]
log(14, 'grades.json', f'negative score: {impossible_low[["student_id","assessment_id","score"]].values.tolist()}', 'set to 0 — cannot have negative grade', len(impossible_low))
grades.loc[grades['score'] < 0, 'score'] = 0

[#14] grades.json — negative score: [['S0001', 'C002-QZ', -10.0]] → set to 0 — cannot have negative grade (1)

In [25]:
# issue 15 grade records for students not in students.csv
valid_sids = set(students['student_id'])
ghost_grades = grades[~grades['student_id'].isin(valid_sids)]
log(15, 'grades.json', f'grade records for {ghost_grades["student_id"].nunique()} student_ids not in students.csv', 'flag with orphan=True — keep for audit, exclude from analysis', ghost_grades['student_id'].nunique())
grades['orphan'] = ~grades['student_id'].isin(valid_sids)

[#15] grades.json — grade records for 0 student_ids not in students.csv → flag with orphan=True — keep for audit, exclude from analysis

In [26]:
# issue 16  grade date stored as string
grades['date'] = pd.to_datetime(grades['date'], errors='coerce')
log(16, 'grades.json', 'date column stored as string', 'Converted to datetime64', None)
 
# issue 17  assessment_id naming inconsistency (C002-QZ vs C002-QZ1)
log(17, 'grades.json', 'assessment_id format varies: some have trailing number, some do not (e.g. C002-QZ vs C002-QZ1)', 'Kept as-is — no single correct canonical form; noted for joins', None)

[#16] grades.json — date column stored as string → Converted to datetime64
[#17] grades.json — assessment_id format varies: some have trailing number, some do not (e.g. C002-QZ vs C002-QZ1) → Kept as-is — no single correct canonical form; noted for joins

#### 4 attendence.xlsx

In [27]:
# Issue 18 — 6 different status encodings across sheets
log(18, 'attendance.xlsx', '6 different status encodings across sheets (attended/Present/P/yes/1/True)', 'Already normalised in Step 1 via STATUS_MAP', None)
 
# Issue 19 — datetime column renamed to "datetime" in 2026-02 sheet
log(19, 'attendance.xlsx', 'Sheet 2026-02 renamed session_datetime to datetime', 'Already renamed in Step 1 during sheet stacking', None)
 
# Issue 20 — null status values after mapping
null_status = attendance['status'].isnull().sum()
log(20, 'attendance.xlsx', f'{null_status} null status values after normalisation', 'Drop rows — attendance status is mandatory for analysis', int(null_status))
attendance = attendance.dropna(subset=['status']).reset_index(drop=True)
 
# Issue 21 — attendance for students not in students.csv
ghost_att = attendance[~attendance['student_id'].isin(valid_sids)]
log(21, 'attendance.xlsx', f'{len(ghost_att)} attendance records for unknown student_ids', 'Drop — cannot attribute attendance to unknown students', len(ghost_att))
attendance = attendance[attendance['student_id'].isin(valid_sids)].reset_index(drop=True)
 
# Issue 22 — session_datetime not parsed as datetime
attendance['session_datetime'] = pd.to_datetime(attendance['session_datetime'], errors='coerce')
null_dt = attendance['session_datetime'].isnull().sum()
log(22, 'attendance.xlsx', f'session_datetime stored as string; {null_dt} nulls after parse', 'Converted to datetime64; null datetimes dropped', int(null_dt))
attendance = attendance.dropna(subset=['session_datetime']).reset_index(drop=True)
 
# Issue 23 — duplicate record_ids across sheets (same session recorded twice)
dup_att = attendance[attendance['record_id'].duplicated(keep=False)]
log(23, 'attendance.xlsx', f'{attendance["record_id"].duplicated().sum()} duplicate record_ids (cross-sheet duplicates)', 'Keep first occurrence', int(attendance['record_id'].duplicated().sum()))
attendance = attendance.drop_duplicates(subset='record_id', keep='first').reset_index(drop=True)

[#18] attendance.xlsx — 6 different status encodings across sheets (attended/Present/P/yes/1/True) → Already normalised in Step 1 via STATUS_MAP
[#19] attendance.xlsx — Sheet 2026-02 renamed session_datetime to datetime → Already renamed in Step 1 during sheet stacking
[#20] attendance.xlsx — 0 null status values after normalisation → Drop rows — attendance status is mandatory for analysis
[#21] attendance.xlsx — 1 attendance records for unknown student_ids → Drop — cannot attribute attendance to unknown students (1)
[#22] attendance.xlsx — session_datetime stored as string; 0 nulls after parse → Converted to datetime64; null datetimes dropped
[#23] attendance.xlsx — 6 duplicate record_ids (cross-sheet duplicates) → Keep first occurrence (6)

#### 5 concepts_performance.csv

In [28]:
 #Issue 24 — score_pct > 100 (max = 142)
cp_high = (cp['score_pct'] > 100).sum()
log(24, 'concepts_performance.csv', f'{cp_high} score_pct values > 100 (max={cp["score_pct"].max()})', 'Cap at 100', int(cp_high))
cp['score_pct'] = cp['score_pct'].clip(upper=100)
 
# Issue 25 — score_pct < 0 (min = -33)
cp_low = (cp['score_pct'] < 0).sum()
log(25, 'concepts_performance.csv', f'{cp_low} score_pct values < 0 (min={cp["score_pct"].min()})', 'Clip to 0', int(cp_low))
cp['score_pct'] = cp['score_pct'].clip(lower=0)
 
# Issue 26 — mastery_status inconsistency: 1761 "failed" rows with score_pct >= 50
mismatch_mask = (cp['mastery_status'] == 'failed') & (cp['score_pct'] >= 50)
log(26, 'concepts_performance.csv', f'{mismatch_mask.sum()} rows have mastery_status=failed but score_pct >= 50', 'Recompute mastery_status from score_pct: passed if >= 50', int(mismatch_mask.sum()))
cp['mastery_status'] = cp['score_pct'].apply(lambda x: 'passed' if x >= 50 else 'failed')
 
# Issue 27 — timestamp stored as string
cp['timestamp'] = pd.to_datetime(cp['timestamp'], errors='coerce')
log(27, 'concepts_performance.csv', 'timestamp stored as string (ISO format)', 'Converted to datetime64', None)
 
# Issue 28 — concepts for students not in students.csv
ghost_cp = cp[~cp['student_id'].isin(valid_sids)]
log(28, 'concepts_performance.csv', f'{len(ghost_cp)} concept records for unknown student_ids', 'Flag with orphan=True', len(ghost_cp))
cp['orphan'] = ~cp['student_id'].isin(valid_sids)

[#24] concepts_performance.csv — 1 score_pct values > 100 (max=142.0) → Cap at 100 (1)
[#25] concepts_performance.csv — 1 score_pct values < 0 (min=-33.0) → Clip to 0 (1)
[#26] concepts_performance.csv — 1761 rows have mastery_status=failed but score_pct >= 50 → Recompute mastery_status from score_pct: passed if >= 50 (1761)
[#27] concepts_performance.csv — timestamp stored as string (ISO format) → Converted to datetime64
[#28] concepts_performance.csv — 0 concept records for unknown student_ids → Flag with orphan=True

#### 6 engagment_events.csv

In [29]:
 # Issue 29 — duration_seconds populated for non-video events
non_video_dur = eng[(eng['event_type'] != 'video_watch') & (eng['duration_seconds'].notnull())]
log(29, 'engagement_events.csv', f'duration_seconds should only apply to video_watch — {len(non_video_dur)} non-video rows have it', 'Set to NaN for all non-video_watch rows', len(non_video_dur))
eng.loc[eng['event_type'] != 'video_watch', 'duration_seconds'] = np.nan
 
# Issue 30 — negative duration_seconds
neg_dur = (eng['duration_seconds'] < 0).sum()
log(30, 'engagement_events.csv', f'{neg_dur} negative duration_seconds values', 'Set to NaN — cannot have negative watch time', int(neg_dur))
eng.loc[eng['duration_seconds'] < 0, 'duration_seconds'] = np.nan
 
# Issue 31 — duration_seconds > 8 hours (28800s) — likely data entry error
extreme_dur = (eng['duration_seconds'] > 28800).sum()
log(31, 'engagement_events.csv', f'{extreme_dur} duration_seconds > 8 hours (implausible single session)', 'Cap at 28800 (8 hours)', int(extreme_dur))
eng['duration_seconds'] = eng['duration_seconds'].clip(upper=28800)
 
# Issue 32 — event_datetime stored as string
eng['event_datetime'] = pd.to_datetime(eng['event_datetime'], errors='coerce')
log(32, 'engagement_events.csv', 'event_datetime stored as string', 'Converted to datetime64', None)
 
# Issue 33 — engagement records for students not in students.csv
ghost_eng = eng[~eng['student_id'].isin(valid_sids)]
log(33, 'engagement_events.csv', f'{len(ghost_eng)} engagement events for unknown student_ids', 'Drop — cannot attribute events to unknown students', len(ghost_eng))
eng = eng[eng['student_id'].isin(valid_sids)].reset_index(drop=True)

[#29] engagement_events.csv — duration_seconds should only apply to video_watch — 0 non-video rows have it → Set to NaN for all non-video_watch rows
[#30] engagement_events.csv — 2 negative duration_seconds values → Set to NaN — cannot have negative watch time (2)
[#31] engagement_events.csv — 1 duration_seconds > 8 hours (implausible single session) → Cap at 28800 (8 hours) (1)
[#32] engagement_events.csv — event_datetime stored as string → Converted to datetime64
[#33] engagement_events.csv — 1 engagement events for unknown student_ids → Drop — cannot attribute events to unknown students (1)

#### 7 assignment_submission.csv

In [30]:
# Issue 34 — 1 null submitted_at value
log(34, 'assignment_submissions.csv', '1 null submitted_at value', 'Drop row — cannot compute lateness without submission time', 1)
subs = subs.dropna(subset=['submitted_at']).reset_index(drop=True)
 
# Issue 35 — is_late flag does not match timestamps (2 mismatches)
subs['deadline']     = pd.to_datetime(subs['deadline'], errors='coerce')
subs['submitted_at'] = pd.to_datetime(subs['submitted_at'], errors='coerce')
subs['is_late_computed'] = subs['submitted_at'] > subs['deadline']
mismatch_late = (subs['is_late'] != subs['is_late_computed']).sum()
log(35, 'assignment_submissions.csv', f'{mismatch_late} rows where is_late flag contradicts submitted_at vs deadline', 'Recompute is_late from timestamps (source of truth)', int(mismatch_late))
subs['is_late'] = subs['is_late_computed']
subs = subs.drop(columns=['is_late_computed'])
 
# Issue 36 — negative time_spent_minutes (1 row)
neg_time = (subs['time_spent_minutes'] < 0).sum()
log(36, 'assignment_submissions.csv', f'{neg_time} negative time_spent_minutes', 'Set to NaN — cannot have negative time', int(neg_time))
subs.loc[subs['time_spent_minutes'] < 0, 'time_spent_minutes'] = np.nan
 
# Issue 37 — cross-file: students with group_id = NaN (from issue #9) have grades/submissions
# These 3 students (GZZ, G77) cannot be linked to a course via the chain
# students.group_id → groups.group_id → courses.course_id
# Their grade and submission records are technically orphaned
orphan_sids = students[students['group_id'].isnull()]['student_id'].tolist()
orphan_subs = subs[subs['student_id'].isin(orphan_sids)]
log(37, 'assignment_submissions.csv + students.csv', f'3 students with invalid group_id have {len(orphan_subs)} submission records that cannot be linked to a course via the chain', 'Flag as orphan=True in subs — keep for audit, exclude from group-level analysis', len(orphan_subs))
subs['orphan'] = subs['student_id'].isin(orphan_sids)

[#34] assignment_submissions.csv — 1 null submitted_at value → Drop row — cannot compute lateness without submission time (1)
[#35] assignment_submissions.csv — 2 rows where is_late flag contradicts submitted_at vs deadline → Recompute is_late from timestamps (source of truth) (2)
[#36] assignment_submissions.csv — 1 negative time_spent_minutes → Set to NaN — cannot have negative time (1)
[#37] assignment_submissions.csv + students.csv — 3 students with invalid group_id have 9 submission records that cannot be linked to a course via the chain → Flag as orphan=True in subs — keep for audit, exclude from group-level analysis (9)

In [31]:
invalid_concept_mask = ~cp['concept_name'].astype(str).str.contains(r'^[\x00-\x7F]+$', na=False)
num_invalid_concepts = invalid_concept_mask.sum()

if num_invalid_concepts > 0:
    if num_invalid_concepts > 0:
        log(29, 'concepts_performance.csv',
            f"{num_invalid_concepts} invalid/corrupted concept_name strings found",
            "Drop row — cannot recover missing/corrupted concept names",
            int(num_invalid_concepts))

        cp = cp[~invalid_concept_mask].copy()
    
    cp = cp[~invalid_concept_mask].copy()

[#29] concepts_performance.csv — 1 invalid/corrupted concept_name strings found → Drop row — cannot recover missing/corrupted concept names (1)

In [32]:
print("\n" + "="*65)
print(f"CLEANING LOG — {len(clean_log)} issues found and handled")
print("="*65)
log_df = pd.DataFrame(clean_log)
print(log_df[['issue','file','description','action']].to_string(index=False))
 
print(f"\n=== FINAL SHAPES AFTER CLEANING ===")
print(f"courses      : {courses.shape}")
print(f"groups       : {groups.shape}")
print(f"students     : {students.shape}")
print(f"grades       : {grades.shape}")
print(f"attendance   : {attendance.shape}")
print(f"concepts     : {cp.shape}")
print(f"engagement   : {eng.shape}")
print(f"submissions  : {subs.shape}")

=================================================================
CLEANING LOG — 38 issues found and handled
=================================================================
 issue                                      file                                                                                                description                                                                          action
     1                                groups.csv                                                                                      duplicaed row for G01                                          keep first occurrence , drop duplicate
     2                                 group.csv                                                                G99 test_group_delete -  unreal test group                                                                drop row entirely
     3                                groups.csv                                                                                    null instructor for G99                                             resolved by dropping G99 (issue #2)
     4                                groups.csv                                                    inconsistent session_time formats (16:00 / 6 PM / 1800)                                                         normalised all to HH:MM
     5                               student.csv                                                                                    4 null full_name values                                                     Impute as "Unknown Student"
     6                              students.csv  Impossible ages: [4, -22, -5, 121, 99, 88] for IDs ['S0023', 'S0209', 'S0453', 'S0478', 'S0362', 'S0074']                                     Replace with NaN, then fill with median age
     7                              students.csv                                                               S0062 has email = "not-an-email" (no @ sign)                                   Replace with NaN — cannot infer correct email
     8                              students.csv                                                                  duplicate student_ids: ['S0074', 'S0362']                   Keep last row (appended duplicates are at bottom — same data)
     9                              students.csv                   students with non-existent group_id: ['S0014', 'S0095', 'S0323'] → ['GZZ', 'G77', 'G77']                      Replace group_id with NaN — cannot assign to unknown group
    10                              students.csv                                      gender has 10 unique encodings (Male/MALE/M/m/male + Female variants)                                                   normalised all to Male/Female
    11                              students.csv                                                                    enrollment_date stored as object/string                                                         converted to datetime64
    12                               grades.json                                                                                        2 null score values                            drop rows — cannot impute a grade without the source
    13                               grades.json                      score > max_score: [['S0002', 'C004-QZ', 187.0, 100], ['S0005', 'C001-QZ', 78.2, 10]]                                                          cap score at max_score
    14                               grades.json                                                              negative score: [['S0001', 'C002-QZ', -10.0]]                                           set to 0 — cannot have negative grade
    15                               grades.json                                                        grade records for 0 student_ids not in students.csv                   flag with orphan=True — keep for audit, exclude from analysis
    16                               grades.json                                                                               date column stored as string                                                         Converted to datetime64
    17                               grades.json             assessment_id format varies: some have trailing number, some do not (e.g. C002-QZ vs C002-QZ1)                  Kept as-is — no single correct canonical form; noted for joins
    18                           attendance.xlsx                                 6 different status encodings across sheets (attended/Present/P/yes/1/True)                                     Already normalised in Step 1 via STATUS_MAP
    19                           attendance.xlsx                                                         Sheet 2026-02 renamed session_datetime to datetime                                 Already renamed in Step 1 during sheet stacking
    20                           attendance.xlsx                                                                   0 null status values after normalisation                         Drop rows — attendance status is mandatory for analysis
    21                           attendance.xlsx                                                               1 attendance records for unknown student_ids                          Drop — cannot attribute attendance to unknown students
    22                           attendance.xlsx                                                     session_datetime stored as string; 0 nulls after parse                                 Converted to datetime64; null datetimes dropped
    23                           attendance.xlsx                                                            6 duplicate record_ids (cross-sheet duplicates)                                                           Keep first occurrence
    24                  concepts_performance.csv                                                                       1 score_pct values > 100 (max=142.0)                                                                      Cap at 100
    25                  concepts_performance.csv                                                                         1 score_pct values < 0 (min=-33.0)                                                                       Clip to 0
    26                  concepts_performance.csv                                                   1761 rows have mastery_status=failed but score_pct >= 50                        Recompute mastery_status from score_pct: passed if >= 50
    27                  concepts_performance.csv                                                                    timestamp stored as string (ISO format)                                                         Converted to datetime64
    28                  concepts_performance.csv                                                                  0 concept records for unknown student_ids                                                           Flag with orphan=True
    29                     engagement_events.csv                               duration_seconds should only apply to video_watch — 0 non-video rows have it                                         Set to NaN for all non-video_watch rows
    30                     engagement_events.csv                                                                         2 negative duration_seconds values                                    Set to NaN — cannot have negative watch time
    31                     engagement_events.csv                                                  1 duration_seconds > 8 hours (implausible single session)                                                          Cap at 28800 (8 hours)
    32                     engagement_events.csv                                                                            event_datetime stored as string                                                         Converted to datetime64
    33                     engagement_events.csv                                                                1 engagement events for unknown student_ids                              Drop — cannot attribute events to unknown students
    34                assignment_submissions.csv                                                                                  1 null submitted_at value                      Drop row — cannot compute lateness without submission time
    35                assignment_submissions.csv                                             2 rows where is_late flag contradicts submitted_at vs deadline                             Recompute is_late from timestamps (source of truth)
    36                assignment_submissions.csv                                                                              1 negative time_spent_minutes                                          Set to NaN — cannot have negative time
    37 assignment_submissions.csv + students.csv 3 students with invalid group_id have 9 submission records that cannot be linked to a course via the chain Flag as orphan=True in subs — keep for audit, exclude from group-level analysis
    29                  concepts_performance.csv                                                             1 invalid/corrupted concept_name strings found                       Drop row — cannot recover missing/corrupted concept names

=== FINAL SHAPES AFTER CLEANING ===
courses      : (7, 8)
groups       : (10, 7)
students     : (500, 8)
grades       : (5500, 11)
attendance   : (13003, 7)
concepts     : (12007, 11)
engagement   : (30865, 6)
submissions  : (1503, 10)

In [33]:
all_datasets = {
    'Courses': courses,
    'Groups': groups,
    'Students': students,
    'Grades': grades,
    'Attendance': attendance,
    'Concepts': cp, 
    'Engagement': eng,
    'Submissions': subs
}

def sanity_check_data(datasets_dict):
    print("="*60)
    print("SMART DATA PROFILING & SANITY CHECK")
    print("="*60)
    
    for name, df in datasets_dict.items():
        print(f"\n: {name}")
        print("-" * 30)
        
        for col in df.columns:
            if df[col].dtype == 'object' or df[col].dtype.name == 'category':
                unique_vals = df[col].dropna().unique()
                if len(unique_vals) <= 20:
                    print(f"🔹 {col} (Categorical) -> Unique Values: {list(unique_vals)}")
                else:
                    print(f"🔹 {col} (Categorical) -> {len(unique_vals)} Unique Values (Too many to list)")
            
            elif pd.api.types.is_numeric_dtype(df[col]):
                print(f"🔸 {col} (Numeric) -> Min: {df[col].min()} | Max: {df[col].max()} | Nulls: {df[col].isnull().sum()}")

sanity_check_data(all_datasets)

============================================================
SMART DATA PROFILING & SANITY CHECK
============================================================

: Courses
------------------------------
🔸 duration_weeks (Numeric) -> Min: 8 | Max: 16 | Nulls: 0
🔸 is_active (Numeric) -> Min: True | Max: True | Nulls: 0

: Groups
------------------------------
🔸 stated_num_students (Numeric) -> Min: 31 | Max: 76 | Nulls: 0

: Students
------------------------------
🔸 age (Numeric) -> Min: 17 | Max: 31 | Nulls: 0

: Grades
------------------------------
🔸 score (Numeric) -> Min: 0.0 | Max: 100.0 | Nulls: 0
🔸 max_score (Numeric) -> Min: 10 | Max: 100 | Nulls: 0
🔸 orphan (Numeric) -> Min: False | Max: False | Nulls: 0

: Attendance
------------------------------

: Concepts
------------------------------
🔸 question_no (Numeric) -> Min: 1 | Max: 4 | Nulls: 0
🔸 score_pct (Numeric) -> Min: 0.0 | Max: 100.0 | Nulls: 0
🔸 orphan (Numeric) -> Min: False | Max: False | Nulls: 0

: Engagement
------------------------------
🔸 duration_seconds (Numeric) -> Min: 20.0 | Max: 28800.0 | Nulls: 22050

: Submissions
------------------------------
🔸 is_late (Numeric) -> Min: False | Max: True | Nulls: 0
🔸 time_spent_minutes (Numeric) -> Min: 10.0 | Max: 255.0 | Nulls: 1
🔸 attempts (Numeric) -> Min: 1 | Max: 3 | Nulls: 0
🔸 orphan (Numeric) -> Min: False | Max: True | Nulls: 0

In [34]:
all_datasets = {
    'Courses': courses,
    'Groups': groups,
    'Students': students,
    'Grades': grades,
    'Attendance': attendance,
    'Concepts': cp, 
    'Engagement': eng,
    'Submissions': subs
}

print("="*60)
print(" INSPECTING UNIQUE VALUES PER COLUMN")
print("="*60)

for name, df in all_datasets.items():
    print(f"\n {name}")
    print("-" * 30)
    
    for col in df.columns:
        unique_vals = df[col].dropna().unique()
        
        if len(unique_vals) <= 20:
            print(f"🔹 {col} ({len(unique_vals)} unique) -> {list(unique_vals)}")
        else:
            print(f"🔹 {col} ({len(unique_vals)} unique) -> [Sample: {list(unique_vals[:5])}...]")

============================================================
 INSPECTING UNIQUE VALUES PER COLUMN
============================================================

 Courses
------------------------------
🔹 course_id (7 unique) -> ['C001', 'C002', 'C003', 'C004', 'C005', 'C006', 'C007']
🔹 course_name (7 unique) -> ['Data Analytics Fundamentals', 'Python Programming', 'Web Development', 'UI/UX Design', 'Digital Marketing', 'Machine Learning Basics', 'Cybersecurity Essentials']
🔹 category (5 unique) -> ['Analytics', 'Programming', 'Design', 'Business', 'Security']
🔹 difficulty_level (3 unique) -> ['Beginner', 'Intermediate', 'Advanced']
🔹 duration_weeks (5 unique) -> [np.int64(12), np.int64(14), np.int64(16), np.int64(10), np.int64(8)]
🔹 short_description (7 unique) -> ['Data Analytics Fundamentals — hands-on analytics track at Kayfa.', 'Python Programming — hands-on programming track at Kayfa.', 'Web Development — hands-on programming track at Kayfa.', 'UI/UX Design — hands-on design track at Kayfa.', 'Digital Marketing — hands-on business track at Kayfa.', 'Machine Learning Basics — hands-on analytics track at Kayfa.', 'Cybersecurity Essentials — hands-on security track at Kayfa.']
🔹 modules (7 unique) -> ['["Spreadsheets & Tabular Data", "Descriptive Statistics", "Data Cleaning", "GroupBy & Aggregation", "Joins & Merges", "Data Visualization Basics"]', '["Variables & Types", "Control Flow", "Functions", "Data Structures", "Recursion", "File I/O", "Error Handling"]', '["HTML & Semantics", "CSS Layout", "JavaScript DOM", "HTTP & APIs", "Responsive Design"]', '["Design Principles", "Wireframing", "Color Theory", "Prototyping", "Usability Testing"]', '["SEO Basics", "Content Strategy", "Paid Ads", "Funnel Analytics"]', '["Regression", "Classification", "Overfitting & Regularization", "Feature Engineering", "Model Evaluation", "Clustering"]', '["Networking Basics", "Cryptography", "Authentication", "Threat Modeling", "Secure Coding"]']
🔹 is_active (1 unique) -> [np.True_]

 Groups
------------------------------
🔹 group_id (10 unique) -> ['G01', 'G02', 'G03', 'G04', 'G05', 'G06', 'G07', 'G08', 'G09', 'G10']
🔹 group_name (10 unique) -> ['Group 01 — C001', 'Group 02 — C001', 'Group 03 — C002', 'Group 04 — C002', 'Group 05 — C003', 'Group 06 — C004', 'Group 07 — C005', 'Group 08 — C006', 'Group 09 — C006', 'Group 10 — C007']
🔹 course_id (7 unique) -> ['C001', 'C002', 'C003', 'C004', 'C005', 'C006', 'C007']
🔹 stated_num_students (9 unique) -> [np.int64(52), np.int64(56), np.int64(67), np.int64(65), np.int64(76), np.int64(70), np.int64(60), np.int64(51), np.int64(31)]
🔹 session_day (5 unique) -> ['Thursday', 'Sunday', 'Saturday', 'Tuesday', 'Wednesday']
🔹 session_time (5 unique) -> ['16:00', '18:00', '17:00', '21:00', '19:00']
🔹 instructor (4 unique) -> ['Eng. Khaled Adel', 'Dr. Mona Saad', 'Dr. Laila ElBaz', 'Eng. Hossam Refaat']

 Students
------------------------------
🔹 student_id (500 unique) -> [Sample: ['S0001', 'S0002', 'S0003', 'S0004', 'S0005']...]
🔹 full_name (403 unique) -> [Sample: ['Hana Gamal', 'Mona Abdelaziz', 'Menna Naguib', 'Aya ElShafei', 'Habiba Mahmoud']...]
🔹 age (15 unique) -> [np.int64(27), np.int64(25), np.int64(20), np.int64(21), np.int64(24), np.int64(18), np.int64(23), np.int64(17), np.int64(22), np.int64(26), np.int64(19), np.int64(28), np.int64(29), np.int64(30), np.int64(31)]
🔹 gender (2 unique) -> ['Male', 'Female']
🔹 city (10 unique) -> ['Mansoura', 'Zagazig', 'Ismailia', 'Giza', 'Asyut', 'Alexandria', 'Port Said', 'Tanta', 'Fayoum', 'Cairo']
🔹 email (404 unique) -> [Sample: ['hana.gamal@kayfa-student.io', 'mona.abdelaziz@kayfa-student.io', 'menna.naguib@kayfa-student.io', 'aya.elshafei@kayfa-student.io', 'habiba.mahmoud@kayfa-student.io']...]
🔹 group_id (10 unique) -> ['G03', 'G06', 'G05', 'G02', 'G01', 'G07', 'G04', 'G08', 'G09', 'G10']
🔹 enrollment_date (20 unique) -> [Timestamp('2025-12-14 00:00:00'), Timestamp('2025-12-03 00:00:00'), Timestamp('2025-12-17 00:00:00'), Timestamp('2025-12-12 00:00:00'), Timestamp('2025-12-06 00:00:00'), Timestamp('2025-12-04 00:00:00'), Timestamp('2025-12-05 00:00:00'), Timestamp('2025-12-02 00:00:00'), Timestamp('2025-12-08 00:00:00'), Timestamp('2025-12-15 00:00:00'), Timestamp('2025-12-18 00:00:00'), Timestamp('2025-12-16 00:00:00'), Timestamp('2025-12-10 00:00:00'), Timestamp('2025-12-20 00:00:00'), Timestamp('2025-12-19 00:00:00'), Timestamp('2025-12-09 00:00:00'), Timestamp('2025-12-01 00:00:00'), Timestamp('2025-12-11 00:00:00'), Timestamp('2025-12-13 00:00:00'), Timestamp('2025-12-07 00:00:00')]

 Grades
------------------------------
🔹 grade_id (5500 unique) -> [Sample: ['GR00001', 'GR00002', 'GR00003', 'GR00004', 'GR00005']...]
🔹 assessment_id (36 unique) -> [Sample: ['C002-QZ', 'C002-AS', 'C002-PR', 'C002-EX', 'C002-EXF']...]
🔹 assessment_title (12 unique) -> ['Quiz 1', 'Quiz 2', 'Quiz 3', 'Quiz 4', 'Assignment 1', 'Assignment 2', 'Assignment 3', 'Practical 1', 'Practical 2', 'Midterm Exam', 'Final Exam', 'Bonus Exam']
🔹 type (4 unique) -> ['quiz', 'assignment', 'practical', 'exam']
🔹 score (613 unique) -> [Sample: [np.float64(0.0), np.float64(69.1), np.float64(84.6), np.float64(88.2), np.float64(67.4)]...]
🔹 max_score (2 unique) -> [np.int64(100), np.int64(10)]
🔹 date (107 unique) -> [Sample: [Timestamp('2025-12-27 00:00:00'), Timestamp('2026-01-10 00:00:00'), Timestamp('2026-01-24 00:00:00'), Timestamp('2026-02-07 00:00:00'), Timestamp('2026-02-21 00:00:00')]...]
🔹 student_id (500 unique) -> [Sample: ['S0001', 'S0002', 'S0003', 'S0004', 'S0005']...]
🔹 course_id (7 unique) -> ['C002', 'C004', 'C003', 'C001', 'C005', 'C006', 'C007']
🔹 group_id (10 unique) -> ['G03', 'G06', 'G05', 'G02', 'G01', 'G07', 'G04', 'G08', 'G09', 'G10']
🔹 orphan (1 unique) -> [np.False_]

 Attendance
------------------------------
🔹 record_id (13003 unique) -> [Sample: ['AT000001', 'AT000002', 'AT000003', 'AT000004', 'AT000005']...]
🔹 student_id (500 unique) -> [Sample: ['S0005', 'S0009', 'S0014', 'S0016', 'S0021']...]
🔹 group_id (10 unique) -> ['G01', 'G02', 'G03', 'G04', 'G05', 'G06', 'G07', 'G08', 'G09', 'G10']
🔹 session_type (4 unique) -> ['session', 'quiz', 'practical', 'exam']
🔹 session_datetime (235 unique) -> [Sample: [Timestamp('2025-12-04 16:00:00'), Timestamp('2025-12-11 16:00:00'), Timestamp('2025-12-18 16:00:00'), Timestamp('2025-12-25 16:00:00'), Timestamp('2025-12-04 18:00:00')]...]
🔹 status (2 unique) -> ['attended', 'absent']
🔹 month (6 unique) -> ['2025-12', '2026-01', '2026-02', '2026-03', '2026-04', '2026-05']

 Concepts
------------------------------
🔹 record_id (12002 unique) -> [Sample: ['CP000001', 'CP000002', 'CP000003', 'CP000004', 'CP000005']...]
🔹 student_id (500 unique) -> [Sample: ['S0001', 'S0002', 'S0003', 'S0004', 'S0005']...]
🔹 course_id (7 unique) -> ['C002', 'C004', 'C003', 'C001', 'C005', 'C006', 'C007']
🔹 assessment_id (18 unique) -> ['C002-QZ', 'C002-EX', 'C002-EXF', 'C004-QZ', 'C004-EX', 'C004-EXF', 'C003-QZ', 'C003-EX', 'C003-EXF', 'C001-QZ', 'C001-EX', 'C001-EXF', 'C005-QZ', 'C005-EX', 'C005-EXF', 'C006-QZ', 'C006-EX', 'C006-EXF']
🔹 question_no (4 unique) -> [np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
🔹 concept_id (33 unique) -> [Sample: ['C002-K01', 'C002-K03', 'C002-K06', 'C002-K05', 'C002-K02']...]
🔹 concept_name (33 unique) -> [Sample: ['Variables & Types', 'Functions', 'File I/O', 'Recursion', 'Control Flow']...]
🔹 score_pct (762 unique) -> [Sample: [np.float64(80.0), np.float64(82.0), np.float64(83.2), np.float64(49.3), np.float64(59.4)]...]
🔹 mastery_status (2 unique) -> ['passed', 'failed']
🔹 timestamp (2992 unique) -> [Sample: [Timestamp('2025-12-27 23:06:24'), Timestamp('2026-01-10 23:06:24'), Timestamp('2026-01-24 23:06:24'), Timestamp('2026-02-07 23:06:24'), Timestamp('2026-05-02 23:06:24')]...]
🔹 orphan (1 unique) -> [np.False_]

 Engagement
------------------------------
🔹 event_id (30857 unique) -> [Sample: ['EV000001', 'EV000002', 'EV000003', 'EV000004', 'EV000005']...]
🔹 student_id (500 unique) -> [Sample: ['S0001', 'S0002', 'S0003', 'S0004', 'S0005']...]
🔹 event_type (5 unique) -> ['quiz_attempt', 'video_watch', 'forum_post', 'login', 'resource_download']
🔹 event_datetime (30831 unique) -> [Sample: [Timestamp('2025-01-01 08:00:00'), Timestamp('2026-04-15 08:24:37'), Timestamp('2026-01-25 17:33:56'), Timestamp('2026-04-08 17:16:22'), Timestamp('2026-05-18 22:50:28')]...]
🔹 duration_seconds (1047 unique) -> [Sample: [np.float64(28800.0), np.float64(590.0), np.float64(863.0), np.float64(442.0), np.float64(267.0)]...]
🔹 device (2 unique) -> ['mobile', 'web']

 Submissions
------------------------------
🔹 submission_id (1500 unique) -> [Sample: ['SUB00001', 'SUB00002', 'SUB00003', 'SUB00004', 'SUB00005']...]
🔹 student_id (500 unique) -> [Sample: ['S0001', 'S0002', 'S0003', 'S0004', 'S0005']...]
🔹 course_id (7 unique) -> ['C002', 'C004', 'C003', 'C001', 'C005', 'C006', 'C007']
🔹 assessment_id (8 unique) -> ['C002-AS', 'C004-AS', 'C003-AS', 'C001-AS', 'C005-AS', 'C006-AS', 'C007-AS', 'C001-ZZ9']
🔹 deadline (30 unique) -> [Sample: [Timestamp('2026-02-21 23:59:00'), Timestamp('2026-03-07 23:59:00'), Timestamp('2026-03-21 23:59:00'), Timestamp('2026-02-15 23:59:00'), Timestamp('2026-03-02 23:59:00')]...]
🔹 submitted_at (1473 unique) -> [Sample: [Timestamp('2026-02-21 18:59:00'), Timestamp('2026-03-07 12:46:00'), Timestamp('2026-03-21 15:45:00'), Timestamp('2026-02-15 16:43:00'), Timestamp('2026-03-02 16:37:00')]...]
🔹 is_late (2 unique) -> [np.False_, np.True_]
🔹 time_spent_minutes (196 unique) -> [Sample: [np.float64(176.0), np.float64(137.0), np.float64(44.0), np.float64(73.0), np.float64(91.0)]...]
🔹 attempts (3 unique) -> [np.int64(1), np.int64(2), np.int64(3)]
🔹 orphan (2 unique) -> [np.False_, np.True_]

# 3- Join files

In [35]:
groups.columns

Index(['group_id', 'group_name', 'course_id', 'stated_num_students',
       'session_day', 'session_time', 'instructor'],
      dtype='str')

In [36]:
# student -> group -> course spine (this will be the main table)
students_full=(
    students.merge(groups[['group_id', 'group_name', 'course_id', 'stated_num_students',
       'session_day', 'session_time', 'instructor']],
       on='group_id',how='left')
    .merge(courses[['course_id','course_name','category',
                    'difficulty_level','duration_weeks']],
           on='course_id', how='left')
)
print("students_full shape:", students_full.shape)
print("Columns:", students_full.columns.tolist())
students_full.head(3)

students_full shape: (500, 18)
Columns: ['student_id', 'full_name', 'age', 'gender', 'city', 'email', 'group_id', 'enrollment_date', 'group_name', 'course_id', 'stated_num_students', 'session_day', 'session_time', 'instructor', 'course_name', 'category', 'difficulty_level', 'duration_weeks']

,student_id,full_name,age,gender,city,email,group_id,enrollment_date,group_name,course_id,stated_num_students,session_day,session_time,instructor,course_name,category,difficulty_level,duration_weeks
0,S0001,Hana Gamal,27,Male,Mansoura,hana.gamal@kayfa-student.io,G03,2025-12-14,Group 03 — C002,C002,67.0,Sunday,18:00,Dr. Laila ElBaz,Python Programming,Programming,Beginner,14.0
1,S0002,Mona Abdelaziz,25,Female,Zagazig,mona.abdelaziz@kayfa-student.io,G06,2025-12-03,Group 06 — C004,C004,56.0,Saturday,17:00,Dr. Mona Saad,UI/UX Design,Design,Beginner,10.0
2,S0003,Menna Naguib,20,Male,Ismailia,menna.naguib@kayfa-student.io,G05,2025-12-17,Group 05 — C003,C003,76.0,Tuesday,18:00,Eng. Khaled Adel,Web Development,Programming,Intermediate,16.0

In [37]:
# grades details
grades_full = (
    grades
    .merge(students_full[['student_id','full_name','age','gender',
                           'city','group_id','group_name',
                           'course_name','category','difficulty_level']],
           on='student_id', how='left')
)
 
# score as percentage of max 
grades_full['score_pct'] = (
    grades_full['score'] / grades_full['max_score'] * 100 # because there is different types of tests with different scores
).round(1)
 
print("\ngrades_full shape:", grades_full.shape)
grades_full[['student_id','full_name','group_name',
                   'course_name','type','score','score_pct']].sample(3)

grades_full shape: (5500, 21)

,student_id,full_name,group_name,course_name,type,score,score_pct
3885,S0354,Habiba Ibrahim,Group 03 — C002,Python Programming,quiz,72.5,72.5
4594,S0418,Mahmoud Ramadan,Group 02 — C001,Data Analytics Fundamentals,practical,57.7,57.7
2947,S0268,Mostafa Ibrahim,Group 05 — C003,Web Development,exam,75.2,75.2

In [38]:
different_max = grades_full[grades_full['max_score'] != 100]
print(different_max[['student_id', 'assessment_id', 'score', 'max_score', 'score_pct']].head())

   student_id assessment_id  score  max_score  score_pct
42      S0005       C001-QZ   10.0         10      100.0

In [39]:
# attendence details
attendance_full = (
    attendance
    .merge(students_full[['student_id','full_name','group_id',
                           'group_name','course_name','instructor']],
           on='student_id', how='left')
)
 
attendance_full['attended_flag'] = (attendance_full['status'] == 'attended').astype(int)
 
print("\nattendance_full shape:", attendance_full.shape)
attendance_full[['student_id','group_name','session_datetime',
                        'status','attended_flag']].head(3)

attendance_full shape: (13003, 13)

  student_id       group_name    session_datetime    status  attended_flag
0      S0005  Group 01 — C001 2025-12-04 16:00:00  attended              1
1      S0009  Group 01 — C001 2025-12-04 16:00:00  attended              1
2      S0014              NaN 2025-12-04 16:00:00  attended              1

In [40]:
# concepts details
cp_full = (
    cp
    .merge(students_full[['student_id','full_name','group_id',
                           'group_name','course_name']],
           on='student_id', how='left')
    .merge(courses[['course_id','course_name']]
           .rename(columns={'course_name':'course_name_from_cp'}),
           on='course_id', how='left')
)
 
print("\ncp_full shape:", cp_full.shape)
cp_full[['student_id','concept_name','score_pct',
               'mastery_status','group_name']].head(3)

cp_full shape: (12007, 16)

  student_id       concept_name  score_pct mastery_status       group_name
0      S0001  Variables & Types       80.0         passed  Group 03 — C002
1      S0001          Functions       82.0         passed  Group 03 — C002
2      S0001           File I/O       83.2         passed  Group 03 — C002

In [41]:
# engagment details
 
eng_full = (
    eng
    .merge(students_full[['student_id','full_name','group_id',
                           'group_name','course_name']],
           on='student_id', how='left')
)
 
eng_full['event_datetime'] = pd.to_datetime(eng_full['event_datetime'], errors='coerce')
eng_full['event_month']    = eng_full['event_datetime'].dt.to_period('M').astype(str)
 
print("\neng_full shape:", eng_full.shape)
eng_full[['student_id','event_type','event_datetime',
                'duration_seconds','group_name']].head(3)

eng_full shape: (30865, 11)

,student_id,event_type,event_datetime,duration_seconds,group_name
0,S0001,quiz_attempt,2025-01-01 08:00:00,NaN,Group 03 — C002
1,S0001,video_watch,2026-04-15 08:24:37,NaN,Group 03 — C002
2,S0001,forum_post,2026-01-25 17:33:56,NaN,Group 03 — C002

In [42]:
# submission details
subs_full = (
    subs
    .merge(students_full[['student_id','full_name','group_id',
                           'group_name','course_name']],
           on='student_id', how='left')
    .merge(grades_full[['student_id','assessment_id','score','score_pct']]
           .rename(columns={'score_pct':'grade_score_pct'}),
           on=['student_id','assessment_id'], how='left')
)
 
subs_full['deadline']     = pd.to_datetime(subs_full['deadline'],     errors='coerce')
subs_full['submitted_at'] = pd.to_datetime(subs_full['submitted_at'], errors='coerce')
subs_full['hours_before_deadline'] = (
    (subs_full['deadline'] - subs_full['submitted_at'])
    .dt.total_seconds() / 3600
).round(1)
 
print("\nsubs_full shape:", subs_full.shape)
subs_full[['student_id','assessment_id','is_late',
                 'hours_before_deadline','grade_score_pct']].head(3)

subs_full shape: (4505, 17)

  student_id assessment_id  is_late  hours_before_deadline  grade_score_pct
0      S0001       C002-AS    False                    5.0             67.4
1      S0001       C002-AS    False                    5.0             61.8
2      S0001       C002-AS    False                    5.0             63.4

In [43]:
# per-student summary table  one row per student with all key mertircs

# attendance rate per student
att_rate = (
    attendance_full
    .groupby('student_id')['attended_flag']
    .agg(sessions_total='count', sessions_attended='sum')
    .reset_index()
)
att_rate['attendance_rate'] = (
    att_rate['sessions_attended'] / att_rate['sessions_total'] * 100
).round(1)
 
# grade metrics per student
grade_metrics = (
    grades_full[grades_full['orphan'] == False]
    .groupby('student_id')['score_pct']
    .agg(avg_grade='mean', min_grade='min', max_grade='max', grade_count='count')
    .reset_index()
    .round(1)
)
 
# engagement metrics per student
eng_metrics = (
    eng_full.groupby('student_id').agg(
        total_events      = ('event_id',       'count'),
        login_count       = ('event_type',     lambda x: (x == 'login').sum()),
        video_watch_count = ('event_type',     lambda x: (x == 'video_watch').sum()),
        total_video_secs  = ('duration_seconds','sum'),
        forum_posts       = ('event_type',     lambda x: (x == 'forum_post').sum()),
    )
    .reset_index()
)
eng_metrics['total_video_mins'] = (eng_metrics['total_video_secs'] / 60).round(1)
 
# failed concepts per student
failed_concepts = (
    cp_full[cp_full['mastery_status'] == 'failed']
    .groupby('student_id')['concept_id']
    .nunique()
    .reset_index()
    .rename(columns={'concept_id': 'failed_concept_count'})
)
 
# late submissions per student
late_subs = (
    subs_full.groupby('student_id')['is_late']
    .agg(total_submissions='count',
         late_submissions=lambda x: x.sum())
    .reset_index()
)
 
# combine everything
student_summary = (
    students_full
    .merge(att_rate[['student_id','sessions_total','sessions_attended','attendance_rate']],
           on='student_id', how='left')
    .merge(grade_metrics[['student_id','avg_grade','min_grade','max_grade','grade_count']],
           on='student_id', how='left')
    .merge(eng_metrics[['student_id','total_events','login_count',
                         'video_watch_count','total_video_mins','forum_posts']],
           on='student_id', how='left')
    .merge(failed_concepts, on='student_id', how='left')
    .merge(late_subs, on='student_id', how='left')
)
 
# fill nulls with 0 for counts
count_cols = ['sessions_total','sessions_attended','attendance_rate',
              'avg_grade','total_events','login_count','video_watch_count',
              'total_video_mins','forum_posts','failed_concept_count',
              'total_submissions','late_submissions']
student_summary[count_cols] = student_summary[count_cols].fillna(0)
 
print("\n=== STUDENT SUMMARY TABLE ===")
print("Shape:", student_summary.shape)
print("Columns:", student_summary.columns.tolist())
student_summary[['student_id','full_name','group_name','course_name',
                        'attendance_rate','avg_grade','login_count',
                        'total_video_mins','failed_concept_count']].head(5)

=== STUDENT SUMMARY TABLE ===
Shape: (500, 33)
Columns: ['student_id', 'full_name', 'age', 'gender', 'city', 'email', 'group_id', 'enrollment_date', 'group_name', 'course_id', 'stated_num_students', 'session_day', 'session_time', 'instructor', 'course_name', 'category', 'difficulty_level', 'duration_weeks', 'sessions_total', 'sessions_attended', 'attendance_rate', 'avg_grade', 'min_grade', 'max_grade', 'grade_count', 'total_events', 'login_count', 'video_watch_count', 'total_video_mins', 'forum_posts', 'failed_concept_count', 'total_submissions', 'late_submissions']

,student_id,full_name,group_name,course_name,attendance_rate,avg_grade,login_count,total_video_mins,failed_concept_count
0,S0001,Hana Gamal,Group 03 — C002,Python Programming,80.8,70.0,16,652.4,1.0
1,S0002,Mona Abdelaziz,Group 06 — C004,UI/UX Design,92.3,86.2,32,309.5,0.0
2,S0003,Menna Naguib,Group 05 — C003,Web Development,84.6,71.4,27,188.6,1.0
3,S0004,Aya ElShafei,Group 02 — C001,Data Analytics Fundamentals,84.6,81.7,27,288.4,0.0
4,S0005,Habiba Mahmoud,Group 01 — C001,Data Analytics Fundamentals,73.1,72.7,17,184.5,0.0

In [44]:
print("\n=== REFERENTIAL INTEGRITY CHECK ===")
print(f"students with no group match      : {student_summary['group_id'].isnull().sum()}")
print(f"students with no grade records    : {(student_summary['grade_count'] == 0).sum()}")
print(f"students with no attendance records: {(student_summary['sessions_total'] == 0).sum()}")
print(f"students with no engagement events : {(student_summary['total_events'] == 0).sum()}")
 
# cross-file break detection — grades where course_id != student's course
grades_with_course = grades_full.merge(
    students_full[['student_id','course_id']].rename(columns={'course_id':'student_course'}),
    on='student_id', how='left'
)
chain_breaks = grades_with_course[
    grades_with_course['course_id'] != grades_with_course['student_course']
]
print(f"Grade records breaking course chain: {len(chain_breaks)}")
 
print("\n=== ALL JOINS COMPLETE ===")
print("Tables ready for analysis:")
print("  students_full    — spine: student + group + course")
print("  grades_full      — grades with full context")
print("  attendance_full  — attendance with full context")
print("  cp_full          — concepts with full context")
print("  eng_full         — engagement with full context")
print("  subs_full        — submissions with grade scores")
print("  student_summary  — one row per student, all metrics")

=== REFERENTIAL INTEGRITY CHECK ===
students with no group match      : 3
students with no grade records    : 0
students with no attendance records: 0
students with no engagement events : 0
Grade records breaking course chain: 33

=== ALL JOINS COMPLETE ===
Tables ready for analysis:
  students_full    — spine: student + group + course
  grades_full      — grades with full context
  attendance_full  — attendance with full context
  cp_full          — concepts with full context
  eng_full         — engagement with full context
  subs_full        — submissions with grade scores
  student_summary  — one row per student, all metrics

# 4- Extract insights , Track over time and cluster

In [45]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [46]:
DARK   = "#353b98"
ACCENT = "#8a91f2"
DANGER = "#ff6b6b"
GREEN  = "#43d9a0"
WHITE  = "#ffffff"
TEXT   = "#1a1d3a"

CHART = dict(
    plot_bgcolor  = WHITE,
    paper_bgcolor = WHITE,
    font_color    = TEXT,
    margin        = dict(t=60, b=50, l=50, r=30),
    height        = 450,
)

#### Q1 Attendence rate per group

In [47]:
# count each group students
group_counts = students_full['group_name'].value_counts().reset_index()
group_counts.columns = ['group_name', 'student_count']  
group_counts

        group_name  student_count
0  Group 04 — C002             65
1  Group 08 — C006             60
2  Group 07 — C005             58
3  Group 06 — C004             56
4  Group 02 — C001             56
5  Group 03 — C002             54
6  Group 09 — C006             51
7  Group 01 — C001             50
8  Group 05 — C003             46
9  Group 10 — C007              1

In [48]:
import plotly.graph_objects as go 

g_att = attendance_full.copy()
g_att['attended_flag'] = (g_att['status'] == 'attended').astype(int)
q1 = g_att.groupby('group_name')['attended_flag'].agg(rate='mean',sessions='count').reset_index()
q1['rate'] = (q1['rate'] * 100).round(1)
platform_avg = round(g_att['attended_flag'].mean() * 100, 1)
q1 = q1.sort_values('rate', ascending=True)

fig = px.bar(q1, x='rate', y='group_name', orientation='h', text='rate',
             color_discrete_sequence=[DARK],
             title='Attendance Rate per Group vs Platform Average',
             labels={'group_name':'','rate':'Attendance Rate (%)'})

fig.update_traces(texttemplate='%{text}%', textposition='outside', textfont_color=TEXT)
fig.update_xaxes(range=[0,105])

fig.add_trace(go.Scatter(
    x=[platform_avg] * len(q1),
    y=q1['group_name'],
    mode='lines',
    line=dict(dash='dash', color=DANGER, width=2), 
    hovertemplate=f'Platform avg: {platform_avg}%<extra></extra>',
    showlegend=False
))

fig.update_layout(**CHART)
fig.show()

"""
INSIGHT: Group 07 (C005) sits at 66.8% — significantly below the platform 
average (which is roughly 80%). It is the only group severely struggling with attendance, 
while most other groups maintain a healthy rate between 78% and 85%. 
Note: Group 10's rate (75%) is statistically insignificant as the cleaning process 
revealed it only contains 1 actual student.

Action: Investigate Group 07 immediately. Low attendance is a leading 
indicator of poor academic performance and requires intervention.
"""

"\nINSIGHT: Group 07 (C005) sits at 66.8% — significantly below the platform \naverage (which is roughly 80%). It is the only group severely struggling with attendance, \nwhile most other groups maintain a healthy rate between 78% and 85%. \nNote: Group 10's rate (75%) is statistically insignificant as the cleaning process \nrevealed it only contains 1 actual student.\n\nAction: Investigate Group 07 immediately. Low attendance is a leading \nindicator of poor academic performance and requires intervention.\n"

#### Q2 — Score distribution by assessment type

In [49]:
grades_full.head()

,grade_id,assessment_id,assessment_title,type,score,max_score,date,student_id,course_id,group_id_x,...,full_name,age,gender,city,group_id_y,group_name,course_name,category,difficulty_level,score_pct
0,GR00001,C002-QZ,Quiz 1,quiz,0.0,100,2025-12-27,S0001,C002,G03,...,Hana Gamal,27,Male,Mansoura,G03,Group 03 — C002,Python Programming,Programming,Beginner,0.0
1,GR00002,C002-QZ,Quiz 2,quiz,69.1,100,2026-01-10,S0001,C002,G03,...,Hana Gamal,27,Male,Mansoura,G03,Group 03 — C002,Python Programming,Programming,Beginner,69.1
2,GR00003,C002-QZ,Quiz 3,quiz,84.6,100,2026-01-24,S0001,C002,G03,...,Hana Gamal,27,Male,Mansoura,G03,Group 03 — C002,Python Programming,Programming,Beginner,84.6
3,GR00004,C002-QZ,Quiz 4,quiz,88.2,100,2026-02-07,S0001,C002,G03,...,Hana Gamal,27,Male,Mansoura,G03,Group 03 — C002,Python Programming,Programming,Beginner,88.2
4,GR00005,C002-AS,Assignment 1,assignment,67.4,100,2026-02-21,S0001,C002,G03,...,Hana Gamal,27,Male,Mansoura,G03,Group 03 — C002,Python Programming,Programming,Beginner,67.4

In [50]:
grades_clean = grades_full[grades_full['orphan'] == False].copy()

type_summary = (grades_clean.groupby('type')['score_pct']
                .agg(mean='mean', count='count').round(1).reset_index())

fig = px.box(
    grades_clean, x='type', y='score_pct',
    color='type',
    color_discrete_map={
        'quiz': ACCENT, 'assignment': DANGER,
        'practical': GREEN, 'exam': DARK
    },
    title='Score Distribution by Assessment Type',
    labels={'type': 'Assessment Type', 'score_pct': 'Score (%)'},
    category_orders={'type': ['quiz', 'assignment', 'practical', 'exam']},
    points='outliers',
)
for _, row in type_summary.iterrows():
    fig.add_trace(go.Scatter(
        x=[row['type']], y=[row['mean']],
        mode='markers+text',
        marker=dict(symbol='diamond', size=12, color=TEXT),
        text=[f"avg {row['mean']:.1f}%"],
        textposition='top center',
        textfont=dict(size=10, color=TEXT),
        showlegend=False,
    ))
fig.update_layout(**CHART, showlegend=False)
fig.show()

"""
INSIGHT: Assignments = lowest avg (65.3%) and highest spread (std=12.9).
Quizzes, practicals and exams cluster tightly around 72-73%.
Action: Review assignment difficulty and add mid-task check-ins.
"""

'\nINSIGHT: Assignments = lowest avg (65.3%) and highest spread (std=12.9).\nQuizzes, practicals and exams cluster tightly around 72-73%.\nAction: Review assignment difficulty and add mid-task check-ins.\n'

#### Q3 — Highest / lowest average grade by course

In [51]:
cn = grades_clean.groupby(['course_id', 'course_name'])['score_pct'].mean().reset_index()
cn

  course_id                  course_name  score_pct
0      C001  Data Analytics Fundamentals  72.532532
1      C002           Python Programming  71.580916
2      C003              Web Development  70.270356
3      C004                 UI/UX Design  71.654383
4      C005            Digital Marketing  59.078213
5      C006      Machine Learning Basics  72.812695
6      C007     Cybersecurity Essentials  76.154545

In [52]:
course_grades = (grades_clean.groupby('course_name')['score_pct']
    .agg(avg='mean', std='std', count='count').reset_index().round(1)
    .sort_values('avg', ascending=True))

# two separate bars: avg grade + std — no error bars, no overlap
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Bar(
    y=course_grades['course_name'],
    x=course_grades['avg'],
    orientation='h',
    name='Avg Grade (%)',
    marker_color=ACCENT,
    text=[f"{v}%  n={int(c)}" for v, c in zip(course_grades['avg'], course_grades['count'])],
    textposition='outside',
    textfont=dict(color=TEXT, size=11),
))

fig.add_trace(go.Bar(
    y=course_grades['course_name'],
    x=course_grades['std'],
    orientation='h',
    name='Spread / Std Dev (%)',
    marker_color=DANGER,
    opacity=0.6,
    text=[f"±{v}%" for v in course_grades['std']],
    textposition='outside',
    textfont=dict(color=TEXT, size=10),
))

fig.update_xaxes(range=[0, 110], title='Score (%)')
fig.update_layout(
    title='Q3 — Average Grade vs Spread by Course  (n = number of assessments)',
    barmode='group',
    legend=dict(orientation='h', y=-0.18),
    **CHART,
)
fig.show()

"""
INSIGHT: Digital Marketing = 59.1% — 13 pp below Machine Learning Basics (72.8%)
and widest spread (std=11.5). Cybersecurity has only 11 records — not reliable.
Action: Digital Marketing needs immediate curriculum review.
"""

'\nINSIGHT: Digital Marketing = 59.1% — 13 pp below Machine Learning Basics (72.8%)\nand widest spread (std=11.5). Cybersecurity has only 11 records — not reliable.\nAction: Digital Marketing needs immediate curriculum review.\n'

#### Q4 — Attendance rate vs average grade

In [53]:
student_summary['att_category'] = pd.cut(
    student_summary['attendance_rate'],
    bins=[-1, 25, 50, 75, 105],
    labels=['Very Low (0-25%)', 'Low (26-50%)', 'Medium (51-75%)', 'High (76-100%)']
)

# 2. نرسم الـ Box Plot
fig = px.box(
    student_summary, 
    x='att_category', 
    y='avg_grade',
    color='att_category',
    title='The Correct View: Grade Distribution by Attendance Level',
    labels={'att_category': 'Attendance Level', 'avg_grade': 'Average Grade (%)'},
    category_orders={'att_category': ['Very Low (0-25%)', 'Low (26-50%)', 'Medium (51-75%)', 'High (76-100%)']}
)

fig.update_layout(**CHART, showlegend=False)
fig.show()
"""
INSIGHT: While the 'High' attendance group has slightly better median grades 
than the 'Low' group, the boxes overlap significantly. This visual confirms 
the weak correlation (r = 0.215) — strong attendance does not guarantee high 
grades, and other factors like engagement must be considered.
"""

"\nINSIGHT: While the 'High' attendance group has slightly better median grades \nthan the 'Low' group, the boxes overlap significantly. This visual confirms \nthe weak correlation (r = 0.215) — strong attendance does not guarantee high \ngrades, and other factors like engagement must be considered.\n"

In [54]:
student_summary['att_bin']   = pd.cut(student_summary['attendance_rate'],
    bins=[-1, 60, 80, 105], labels=['Low (<60%)', 'Medium (60-80%)', 'High (>80%)'])
student_summary['grade_bin'] = pd.cut(student_summary['avg_grade'],
    bins=[-1, 55, 70, 105], labels=['Weak (<55%)', 'Pass (55-70%)', 'Strong (>70%)'])

hm = (student_summary.groupby(['grade_bin', 'att_bin'], observed=True)
      .size().reset_index(name='count'))
hm_pivot = hm.pivot(index='grade_bin', columns='att_bin', values='count').fillna(0)
hm_pivot = hm_pivot.reindex(
    index=['Weak (<55%)', 'Pass (55-70%)', 'Strong (>70%)'],
    columns=['Low (<60%)', 'Medium (60-80%)', 'High (>80%)']
)

fig = px.imshow(
    hm_pivot,
    text_auto=True,
    color_continuous_scale=[[0, '#e8eaff'], [0.4, ACCENT], [1, DARK]],
    zmin=0,
    title='Attendance Band vs Grade Band (number of students)',
    labels=dict(x='Attendance Level', y='Grade Level', color='Students'),
)
fig.update_traces(textfont_color='#1a1d3a')
fig.update_layout(**CHART)
fig.show()

"""
INSIGHT: High attendance + Strong grades = 122 students (biggest cell).
But 67 students with High attendance still score Pass or below.
Action: These 67 students attend but don't perform — they need learning support,
not attendance nudges.
"""
"""
INSIGHT: The heatmap reveals the weak correlation (r = 0.215) clearly. 
Notice the 'High (>75%)' attendance column: students are scattered across all grade 
levels, not just 'Excellent'. Simply showing up does not guarantee passing.
Action: Investigate the students in the (High Attendance + Fail) square to see 
what learning barriers they face despite attending sessions.
"""

"\nINSIGHT: The heatmap reveals the weak correlation (r = 0.215) clearly. \nNotice the 'High (>75%)' attendance column: students are scattered across all grade \nlevels, not just 'Excellent'. Simply showing up does not guarantee passing.\nAction: Investigate the students in the (High Attendance + Fail) square to see \nwhat learning barriers they face despite attending sessions.\n"

In [55]:
from scipy.stats import spearmanr
from sklearn.feature_selection import mutual_info_regression

# 1. Spearman Correlation
corr_sp, p_val = spearmanr(student_summary['attendance_rate'], student_summary['avg_grade'])
print(f"Spearman Correlation: {corr_sp:.3f}")

# 2. Mutual Information
mi = mutual_info_regression(student_summary[['attendance_rate']], student_summary['avg_grade'])
print(f"Mutual Information Score: {mi[0]:.3f}")

Spearman Correlation: 0.426
Mutual Information Score: 0.115

In [56]:
corr_val = student_summary[['attendance_rate','avg_grade']].corr().iloc[0,1]

fig = px.scatter(
    student_summary, 
    x='attendance_rate', 
    y='avg_grade',
    color='course_name', 
    trendline='ols', 
    trendline_scope='overall',  
    title=f'Attendance vs Grade (Pearson r = {corr_val:.3f})',
    labels={'attendance_rate':'Attendance Rate (%)','avg_grade':'Average Grade (%)','course_name':'Course'},
    opacity=0.7,
    color_discrete_sequence=px.colors.qualitative.Pastel
)

fig.update_traces(line=dict(color=DARK, width=4), selector=dict(mode='lines'))

fig.update_layout(**CHART)
fig.show()

"""
INSIGHT: The OLS trendline mathematically confirms a very weak relationship. 
1. R-squared (0.046): Attendance explains only 4.6% of the variance in student grades, leaving 95.4% to be driven by other hidden factors.
2. Slope (0.09): A 10% increase in attendance yields less than a 1% increase in the final grade.
3. Intercept (63.25%): The model predicts a passing grade (~63%) even for a student with zero attendance.

Action: Shift retention strategies away from basic attendance tracking. We must prioritize active engagement metrics (video completion, assignment submissions) to effectively identify and help at-risk students.
"""

'\nINSIGHT: The OLS trendline mathematically confirms a very weak relationship. \n1. R-squared (0.046): Attendance explains only 4.6% of the variance in student grades, leaving 95.4% to be driven by other hidden factors.\n2. Slope (0.09): A 10% increase in attendance yields less than a 1% increase in the final grade.\n3. Intercept (63.25%): The model predicts a passing grade (~63%) even for a student with zero attendance.\n\nAction: Shift retention strategies away from basic attendance tracking. We must prioritize active engagement metrics (video completion, assignment submissions) to effectively identify and help at-risk students.\n'

#### Q5 — Engagement vs academic performance

In [57]:
fig = px.scatter(student_summary, x='total_video_mins', y='avg_grade',
                 color='login_count', color_continuous_scale=[[0,ACCENT],[1,DARK]],
                 trendline='ols',
                 title='Video Watch Time vs Grade (coloured by Login Count)',
                 labels={'total_video_mins':'Total Video Watch Time (mins)','avg_grade':'Average Grade (%)','login_count':'Login Count'},
                 opacity=0.7)
fig.update_layout(**CHART)
fig.show()
"""
INSIGHT: Video time r = 0.41, login frequency r = 0.38 with grade — both moderate.
Consistent platform presence is associated with better outcomes.
Action: Promote video completion tracking as an early-warning engagement metric.
"""

'\nINSIGHT: Video time r = 0.41, login frequency r = 0.38 with grade — both moderate.\nConsistent platform presence is associated with better outcomes.\nAction: Promote video completion tracking as an early-warning engagement metric.\n'

In [58]:
r_video = student_summary[['total_video_mins', 'avg_grade']].corr().iloc[0, 1]
r_login = student_summary[['login_count', 'avg_grade']].corr().iloc[0, 1]

# chart A — video
fig = px.scatter(
    student_summary, x='total_video_mins', y='avg_grade',
    color='attendance_rate',
    color_continuous_scale=[[0, DANGER], [0.5, ACCENT], [1, GREEN]],
    trendline='ols',
    title=f'Q5a — Video Watch Time vs Grade  |  r = {r_video:.3f}',
    labels={
        'total_video_mins': 'Total Video Watch (mins)',
        'avg_grade': 'Average Grade (%)',
        'attendance_rate': 'Attendance %',
    },
    opacity=0.7,
)
fig.update_traces(line=dict(color=DARK, width=3), selector=dict(mode='lines'))
fig.update_layout(**CHART)
fig.show()

# chart B — login
fig = px.scatter(
    student_summary, x='login_count', y='avg_grade',
    color='total_video_mins',
    color_continuous_scale=[[0, ACCENT], [1, DARK]],
    trendline='ols',
    title=f'Q5b — Login Frequency vs Grade  |  r = {r_login:.3f}',
    labels={
        'login_count': 'Login Count',
        'avg_grade': 'Average Grade (%)',
        'total_video_mins': 'Video Mins',
    },
    opacity=0.7,
)
fig.update_traces(line=dict(color=DANGER, width=3), selector=dict(mode='lines'))
fig.update_layout(**CHART)
fig.show()

"""
INSIGHT: Both correlate moderately with grade (video r=0.41, login r=0.38).
Students who engage consistently on the platform score better.
Action: Track video completion rate as an early-warning metric per week.
"""

'\nINSIGHT: Both correlate moderately with grade (video r=0.41, login r=0.38).\nStudents who engage consistently on the platform score better.\nAction: Track video completion rate as an early-warning metric per week.\n'

#### Q6 — Concept failure rates

In [59]:
concept_fail = (cp_full.groupby(['concept_name','course_id'])['mastery_status']
    .apply(lambda x: round((x=='failed').sum()/len(x)*100,1)).reset_index())
concept_fail.columns = ['concept_name','course_id','fail_rate']
concept_fail = concept_fail.merge(courses[['course_id','course_name']],on='course_id',how='left').sort_values('fail_rate',ascending=True)
 
fig = px.bar(concept_fail, x='fail_rate', y='concept_name', orientation='h',
             color='course_name', text='fail_rate',
             title='Concept Failure Rate Across Platform',
             labels={'concept_name':'','fail_rate':'Failure Rate (%)','course_name':'Course'})
fig.update_traces(texttemplate='%{text}%', textposition='outside', textfont_color=TEXT)
fig.update_xaxes(range=[0,80])
fig.update_layout(**CHART)
fig.show()
"""
INSIGHT: Recursion (C002) has 66.7% failure rate — 3x higher than the next worst concept.
It is the single biggest curriculum weak spot on the platform.
Action: Redesign the Recursion module immediately — more worked examples, dedicated
practice, checkpoint quiz before proceeding.
"""

'\nINSIGHT: Recursion (C002) has 66.7% failure rate — 3x higher than the next worst concept.\nIt is the single biggest curriculum weak spot on the platform.\nAction: Redesign the Recursion module immediately — more worked examples, dedicated\npractice, checkpoint quiz before proceeding.\n'

In [76]:
# getting unique concepts per course
concepts_per_course = cp_full.groupby('course_name')['concept_name'].nunique().reset_index()
concepts_per_course.columns = ['course_name', 'unique_concept_count']
concepts_per_course = concepts_per_course.sort_values('unique_concept_count', ascending=False)
concepts_per_course

                   course_name  unique_concept_count
4           Python Programming                     7
1  Data Analytics Fundamentals                     6
0     Cybersecurity Essentials                     6
3      Machine Learning Basics                     6
5                 UI/UX Design                     5
6              Web Development                     5
2            Digital Marketing                     4

In [78]:
# calculate failure rate for machine learning basics
ml_concepts = cp_full[cp_full['course_name'] == 'Machine Learning Basics']
ml_fail_rate = (ml_concepts['mastery_status'] == 'failed').mean()   
print(f"Machine Learning Basics Concept Failure Rate: {ml_fail_rate:.1%}")

Machine Learning Basics Concept Failure Rate: 7.1%

In [77]:
# شوفي الـ courses الموجودة في الـ concepts_performance
print(cp['course_id'].unique())

print(cp.groupby('course_id').size().sort_values(ascending=False))

<ArrowStringArray>
['C002', 'C004', 'C003', 'C001', 'C005', 'C006', 'C007']
Length: 7, dtype: str
course_id
C002    2881
C006    2665
C001    2594
C005    1394
C004    1345
C003    1104
C007      24
dtype: int64

#### Q7 — Recursion mastery over time

In [61]:
recursion = cp_full[cp_full['concept_name'] == 'Recursion'].copy()
recursion['timestamp'] = pd.to_datetime(recursion['timestamp'], errors='coerce')
recursion['month'] = recursion['timestamp'].dt.to_period('M').astype(str)
rec_trend = (recursion.groupby('month')
    .agg(avg_mastery=('score_pct','mean')).reset_index().round(1))
 
fig = px.line(rec_trend, x='month', y='avg_mastery', markers=True, text='avg_mastery',
              title='Recursion Concept Mastery Over Time (C002)',
              labels={'month':'Month','avg_mastery':'Avg Mastery Score (%)'},
              color_discrete_sequence=[DANGER])
fig.update_traces(textposition='top center', textfont_color=TEXT, line_width=3, marker_size=9)
fig.add_hline(y=50, line_dash='dash', line_color=DARK,
              annotation_text='Pass threshold (50%)', annotation_position='top right')
fig.update_yaxes(range=[0,80])
fig.update_layout(**CHART)
fig.show()
"""
INSIGHT: Recursion mastery is flat and persistently below the pass threshold —
students are not improving. This is a systemic failure, not a one-time difficulty spike.
Action: The current teaching approach is not working. Restructure the module and retest.
"""

'\nINSIGHT: Recursion mastery is flat and persistently below the pass threshold —\nstudents are not improving. This is a systemic failure, not a one-time difficulty spike.\nAction: The current teaching approach is not working. Restructure the module and retest.\n'

In [62]:
recursion = cp_full[cp_full['concept_name'] == 'Recursion'].copy()
recursion['timestamp'] = pd.to_datetime(recursion['timestamp'], errors='coerce')
recursion['month']     = recursion['timestamp'].dt.to_period('M').astype(str)

rec_trend = (
    recursion.groupby('month')
    .agg(
        avg_mastery = ('score_pct', 'mean'),
        pass_rate   = ('mastery_status', lambda x: round((x == 'passed').sum() / len(x) * 100, 1)),
    )
    .reset_index().round(1)
)

fig = go.Figure()
fig.add_trace(go.Bar(
    x=rec_trend['month'], y=rec_trend['pass_rate'],
    name='Pass Rate (%)', marker_color=ACCENT, opacity=0.5,
))
fig.add_trace(go.Scatter(
    x=rec_trend['month'], y=rec_trend['avg_mastery'],
    mode='lines+markers+text',
    name='Avg Mastery Score',
    line=dict(color=DANGER, width=3),
    marker=dict(size=9, color=DANGER),
    text=rec_trend['avg_mastery'].astype(str),
    textposition='top center',
    textfont=dict(color=TEXT, size=10),
))
fig.add_hline(y=50, line_dash='dash', line_color=DARK,
              annotation_text='Pass threshold (50%)',
              annotation_position='top right')
fig.update_layout(
    title='Recursion Mastery Over Time: Score + Pass Rate',
    xaxis_title='Month',
    yaxis_title='%',
    legend=dict(orientation='h', y=-0.2),
    **CHART,
)
fig.show()

"""
INSIGHT: Both avg mastery and pass rate are flat and below threshold throughout the term.
Students are not improving — the teaching approach is not working.
Action: Restructure the Recursion module and retest before end of term.
"""

'\nINSIGHT: Both avg mastery and pass rate are flat and below threshold throughout the term.\nStudents are not improving — the teaching approach is not working.\nAction: Restructure the Recursion module and retest before end of term.\n'

#### Q8 — Late submissions vs score

In [63]:
subs_full['hours_before_deadline'] = (
    (subs_full['deadline'] - subs_full['submitted_at']).dt.total_seconds() / 3600
).round(1)
 
fig = px.scatter(subs_full.dropna(subset=['grade_score_pct']),
                 x='hours_before_deadline', y='grade_score_pct',
                 color='is_late',
                 color_discrete_map={True:'red', False:'green'},
                 trendline='ols',
                 title=' Submission Timing vs Score',
                 labels={'hours_before_deadline':'Hours Before Deadline (negative = late)',
                         'grade_score_pct':'Assignment Score (%)','is_late':'Late Submission'},
                 opacity=0.65)
fig.add_vline(x=0, line_dash='dash', line_color=DARK,
              annotation_text='Deadline', annotation_position='top right')
fig.update_layout(**CHART)
fig.show()
"""
INSIGHT: Late submissions average 62.1% vs 67.1% on-time — a 4.9 pp gap.
Earlier submission is associated with higher scores.
Action: Automated reminders 48h and 24h before deadlines.
"""

'\nINSIGHT: Late submissions average 62.1% vs 67.1% on-time — a 4.9 pp gap.\nEarlier submission is associated with higher scores.\nAction: Automated reminders 48h and 24h before deadlines.\n'

In [64]:
import pandas as pd
import plotly.express as px

bins = [-float('inf'), 0, 12, 48, float('inf')]
labels = ['Late (< 0h)', 'Last Minute (0-12h)', 'On Time (12-48h)', 'Early (> 48h)']

subs_full['timing_category'] = pd.cut(
    subs_full['hours_before_deadline'],
    bins=bins,
    labels=labels
)

fig = px.box(
    subs_full.dropna(subset=['grade_score_pct']),
    x='timing_category',
    y='grade_score_pct',
    color='timing_category',
    title='Impact of Submission Timing on Assignment Scores',
    labels={
        'timing_category': 'Submission Behavior',
        'grade_score_pct': 'Assignment Score (%)'
    },
    category_orders={'timing_category': labels},
    color_discrete_sequence=['#EF553B', '#FFA15A', '#00CC96', '#636EFA'] 
)
fig.update_traces(boxmean='sd') 
try:
    fig.update_layout(**CHART, showlegend=False)
except NameError:
    fig.update_layout(showlegend=False)
#fig.update_traces(boxmean=True) 
fig.update_layout(**CHART, showlegend=False)
fig.show()
"""
INSIGHT: While late submissions do not result in outright failure, they introduce a clear "Penalty of Rushing." 
Students who submit late or at the last minute lose an average of 6 to 7 percentage points on their final score.
Conversely, students who submit early benefit from a time buffer to review and refine their work, consistently yielding higher grades.
"""

'\nINSIGHT: While late submissions do not result in outright failure, they introduce a clear "Penalty of Rushing." \nStudents who submit late or at the last minute lose an average of 6 to 7 percentage points on their final score.\nConversely, students who submit early benefit from a time buffer to review and refine their work, consistently yielding higher grades.\n'

In [65]:
# Quick statistical summary (including mean and std)
stats_summary = subs_full.groupby('timing_category')['grade_score_pct'].describe()[['count', 'mean', 'std']]
print(stats_summary)

                      count       mean        std
timing_category
Late (< 0h)          1617.0  62.168707  12.992661
Last Minute (0-12h)  1662.0  65.763478  12.684450
On Time (12-48h)     1225.0  68.778122  11.871152

#### Q9 — Attendance & engagement over 6-month term

In [66]:
att_time = attendance_full.copy()
att_time['session_datetime'] = pd.to_datetime(att_time['session_datetime'], errors='coerce')
att_time['month'] = att_time['session_datetime'].dt.to_period('M').astype(str)
att_monthly = (att_time.groupby('month')['attended_flag'].mean().reset_index())
att_monthly['attendance_rate'] = (att_monthly['attended_flag'] * 100).round(1)
att_monthly = att_monthly[att_monthly['month'].between('2025-12', '2026-06')]

eng_full['event_month'] = eng_full['event_datetime'].dt.to_period('M').astype(str)
eng_monthly = (eng_full[eng_full['event_month'].between('2025-12', '2026-06')]
    .groupby('event_month').size().reset_index(name='event_count')
    .rename(columns={'event_month': 'month'}))

ts = att_monthly.merge(eng_monthly, on='month', how='outer').sort_values('month')

fig = go.Figure()
fig.add_trace(go.Scatter(
    x=ts['month'], y=ts['attendance_rate'],
    mode='lines+markers+text',
    name='Attendance Rate (%)',
    line=dict(color=DARK, width=3),
    marker=dict(size=9),
    text=ts['attendance_rate'].astype(str),
    textposition='top center',
    textfont=dict(size=9, color=DARK),
    yaxis='y1',
))
fig.add_trace(go.Bar(
    x=ts['month'], y=ts['event_count'],
    name='Engagement Events',
    marker_color=ACCENT,
    opacity=0.5,
    yaxis='y2',
))
fig.update_layout(
    title='Monthly Attendance Rate + Engagement Events Over the Term',
    xaxis_title='Month',
    yaxis=dict(title='Attendance Rate (%)', range=[50, 95]),
    yaxis2=dict(title='Engagement Events', overlaying='y', side='right'),
    legend=dict(orientation='h', y=-0.2),
    plot_bgcolor=WHITE, paper_bgcolor=WHITE, font_color=TEXT,
    margin=dict(t=60, b=60, l=50, r=60),
    height=450,
)
fig.add_annotation(
    x='2026-03', y=62.2,
    text='March dip: 62.2%\n(both metrics fall)',
    font=dict(size=11, color=DANGER),
    showarrow=True, arrowcolor=DANGER,
    bgcolor='rgba(255,255,255,0.85)',
    bordercolor=DANGER, borderpad=5,
)
fig.show()

"""
INSIGHT: Both attendance (62.2%) and engagement collapse together in March.
This is a cohort-wide event — likely Ramadan or exam period overlap.
Action: Provide async/recorded sessions for known disruption windows.
"""

'\nINSIGHT: Both attendance (62.2%) and engagement collapse together in March.\nThis is a cohort-wide event — likely Ramadan or exam period overlap.\nAction: Provide async/recorded sessions for known disruption windows.\n'

#### Q10 — Age bands vs outcomes

In [67]:
student_summary['age_group'] = pd.cut(student_summary['age'],
    bins=[17, 22, 27, 35, 100], labels=['18-22', '23-27', '28-35', '36+'])

age_g = student_summary.groupby('age_group', observed=True).agg(
    avg_grade       = ('avg_grade', 'mean'),
    attendance_rate = ('attendance_rate', 'mean'),
    count           = ('student_id', 'count'),
).reset_index().round(1)

# video mins normalized to 0-100 scale for comparison
video_max = student_summary['total_video_mins'].max()
age_video = (student_summary.groupby('age_group', observed=True)['total_video_mins']
             .mean().reset_index())
age_video['video_pct'] = (age_video['total_video_mins'] / video_max * 100).round(1)
age_g = age_g.merge(age_video[['age_group', 'video_pct']], on='age_group')

fig = px.bar(
    age_g.melt(id_vars='age_group', value_vars=['avg_grade', 'attendance_rate', 'video_pct']),
    x='age_group', y='value', color='variable',
    barmode='group', text='value',
    color_discrete_map={
        'avg_grade': DARK,
        'attendance_rate': ACCENT,
        'video_pct': GREEN,
    },
    title='Q10 — Age Band Outcomes: Grade · Attendance · Video Engagement (normalized 0-100)',
    labels={'age_group': 'Age Group', 'value': 'Score / %', 'variable': 'Metric'},
)
fig.update_traces(texttemplate='%{text:.0f}', textposition='outside', textfont_color=TEXT)
fig.update_layout(**CHART)

# rename legend labels
newnames = {'avg_grade': 'Avg Grade (%)', 'attendance_rate': 'Attendance (%)', 'video_pct': 'Video Engagement (norm)'}
fig.for_each_trace(lambda t: t.update(name=newnames.get(t.name, t.name)))
fig.show()

"""
INSIGHT: 28-35 band performs best across all 3 metrics. 18-22 weakest on attendance.
Age has a weak but visible effect. Action: Younger students need attendance nudges;
older students need time-flexible scheduling options.
"""

'\nINSIGHT: 28-35 band performs best across all 3 metrics. 18-22 weakest on attendance.\nAge has a weak but visible effect. Action: Younger students need attendance nudges;\nolder students need time-flexible scheduling options.\n'

#### Q11 — Student segmentation (KMeans k=4)

In [68]:
cluster_features = ['attendance_rate', 'avg_grade', 'login_count',
                    'total_video_mins', 'failed_concept_count']
X        = student_summary[cluster_features].fillna(0)
scaler   = StandardScaler()
X_scaled = scaler.fit_transform(X)
kmeans   = KMeans(n_clusters=4, random_state=42, n_init=10)
student_summary['cluster'] = kmeans.fit_predict(X_scaled)

label_map = {
    0: 'High Achievers',
    2: 'Average Engaged',
    1: 'Silent Strugglers',
    3: 'At-Risk',
}
student_summary['segment'] = student_summary['cluster'].map(label_map)

COLOR_MAP = {
    'High Achievers': GREEN, 'Average Engaged': ACCENT,
    'At-Risk': DANGER, 'Outlier': DARK,
}

fig = px.scatter(
    student_summary, x='attendance_rate', y='avg_grade',
    color='segment', size='failed_concept_count',
    size_max=20,
    hover_data=['full_name', 'group_name', 'login_count', 'total_video_mins'],
    color_discrete_map=COLOR_MAP,
    title='Student Segmentation: Attendance vs Grade  (size = failed concepts)',
    labels={
        'attendance_rate': 'Attendance Rate (%)',
        'avg_grade': 'Average Grade (%)',
        'segment': 'Segment',
        'failed_concept_count': 'Failed Concepts',
    },
    opacity=0.8,
)
fig.update_layout(**CHART)
fig.show()

# cluster profile table
profiles = student_summary.groupby('segment')[cluster_features + ['student_id']].agg(
    attendance_rate        = ('attendance_rate', 'mean'),
    avg_grade              = ('avg_grade', 'mean'),
    login_count            = ('login_count', 'mean'),
    total_video_mins       = ('total_video_mins', 'mean'),
    failed_concept_count   = ('failed_concept_count', 'mean'),
    count                  = ('student_id', 'count'),
).reset_index().round(1)
print("\nCluster Profiles:")
print(profiles[['segment','attendance_rate','avg_grade','login_count',
                'total_video_mins','failed_concept_count','count']].to_string(index=False))

"""
INSIGHT: 4 segments بناءً على الداتا الفعلية:
  High Achievers    (cluster 0): att 84.4%, grade 76.3%, 0.6 failed concepts
  Average Engaged   (cluster 2): att 73.3%, grade 71.3%, 0.7 failed concepts
  Silent Strugglers (cluster 1): att 80.3%, grade 64.1%, 3.3 failed concepts
                                 — بييجوا بانتظام لكن مش فاهمين المحتوى
  At-Risk           (cluster 3): att 60.5%, grade 58.4%, 3.3 failed concepts
                                 — مش بييجوا ومش فاهمين

الـ Silent Strugglers محتاجين learning intervention مش attendance nudges.
الـ At-Risk محتاجين الاتنين مع بعض.
Action: ابدأ بالـ At-Risk فوراً، وعمل learning support program للـ Silent Strugglers.
"""

Cluster Profiles:
          segment  attendance_rate  avg_grade  login_count  total_video_mins  failed_concept_count  count
          At-Risk             60.5       58.4         16.4             115.7                   3.3     67
  Average Engaged             73.3       71.3         19.7             143.3                   0.7    172
   High Achievers             84.4       76.3         26.1             234.1                   0.6    192
Silent Strugglers             80.3       64.1         22.5             172.8                   3.3     69

'\nINSIGHT: 4 segments بناءً على الداتا الفعلية:\n  High Achievers    (cluster 0): att 84.4%, grade 76.3%, 0.6 failed concepts\n  Average Engaged   (cluster 2): att 73.3%, grade 71.3%, 0.7 failed concepts\n  Silent Strugglers (cluster 1): att 80.3%, grade 64.1%, 3.3 failed concepts\n                                 — بييجوا بانتظام لكن مش فاهمين المحتوى\n  At-Risk           (cluster 3): att 60.5%, grade 58.4%, 3.3 failed concepts\n                                 — مش بييجوا ومش فاهمين\n\nالـ Silent Strugglers محتاجين learning intervention مش attendance nudges.\nالـ At-Risk محتاجين الاتنين مع بعض.\nAction: ابدأ بالـ At-Risk فوراً، وعمل learning support program للـ Silent Strugglers.\n'

In [ ]:

ATT_HIGH   = 75   
GRADE_HIGH = 70   

def assign_segment(row):
    att   = row['attendance_rate']
    grade = row['avg_grade']

    if att >= ATT_HIGH and grade >= GRADE_HIGH:
        return 'High Achievers'        
    elif att >= ATT_HIGH and grade < GRADE_HIGH:
        return 'Silent Strugglers'     
    elif att < ATT_HIGH and grade >= GRADE_HIGH:
        return 'Average Engaged'    
    else:
        return 'At-Risk'              

student_summary['segment'] = student_summary.apply(assign_segment, axis=1)

COLOR_MAP = {
    'High Achievers'   : GREEN,
    'Average Engaged'  : ACCENT,
    'Silent Strugglers': '#f59e0b',   
    'At-Risk'          : DANGER,
}

fig = px.scatter(
    student_summary,
    x='attendance_rate', y='avg_grade',
    color='segment', size='failed_concept_count',
    size_max=20,
    hover_data=['full_name', 'group_name', 'login_count',
                'total_video_mins', 'failed_concept_count'],
    color_discrete_map=COLOR_MAP,
    title='Student Segmentation: Attendance vs Grade  (size = failed concepts)',
    labels={
        'attendance_rate'     : 'Attendance Rate (%)',
        'avg_grade'           : 'Average Grade (%)',
        'segment'             : 'Segment',
        'failed_concept_count': 'Failed Concepts',
    },
    opacity=0.8,
)

fig.add_hline(y=GRADE_HIGH, line_dash='dash', line_color='gray', line_width=1,
              annotation_text=f'Grade threshold ({GRADE_HIGH}%)',
              annotation_position='top left')
fig.add_vline(x=ATT_HIGH, line_dash='dash', line_color='gray', line_width=1,
              annotation_text=f'Attendance threshold ({ATT_HIGH}%)',
              annotation_position='top right')

fig.update_layout(**CHART)
fig.show()

# ── Cluster profile table ────────────────────────────────────────────────────
profiles = (
    student_summary
    .groupby('segment')
    .agg(
        attendance_rate      = ('attendance_rate',      'mean'),
        avg_grade            = ('avg_grade',            'mean'),
        login_count          = ('login_count',          'mean'),
        total_video_mins     = ('total_video_mins',     'mean'),
        failed_concept_count = ('failed_concept_count', 'mean'),
        count                = ('student_id',           'count'),
    )
    .reset_index()
    .round(1)
)
print("\nSegment Profiles:")
print(profiles[['segment', 'attendance_rate', 'avg_grade',
                'login_count', 'total_video_mins',
                'failed_concept_count', 'count']].to_string(index=False))

Segment Profiles:
          segment  attendance_rate  avg_grade  login_count  total_video_mins  failed_concept_count  count
          At-Risk             63.1       61.5         19.0             135.0                   2.5    117
  Average Engaged             68.0       75.0         22.2             174.4                   0.6     75
   High Achievers             84.8       76.5         23.8             209.0                   0.7    205
Silent Strugglers             83.0       65.4         22.3             170.4                   2.0    103

#### Q12 — True vs stated group sizes

In [70]:
real_counts = (students[students['group_id'].notna()]
    .groupby('group_id').size().reset_index(name='real_count'))
q12 = groups.merge(real_counts, on='group_id', how='left').fillna(0)
q12['real_count'] = q12['real_count'].astype(int)
q12['diff']       = q12['real_count'] - q12['stated_num_students']
q12['flag']       = q12['diff'].apply(
    lambda d: 'Under-reported' if d > 5 else ('Over-reported' if d < -5 else 'Accurate'))
q12_sorted = q12.sort_values('diff', ascending=True)

fig = px.bar(
    q12_sorted, x='diff', y='group_name', orientation='h',
    text='diff', color='flag',
    color_discrete_map={'Accurate': GREEN, 'Under-reported': ACCENT, 'Over-reported': DANGER},
    title='Group Size Discrepancy: Real − Stated Count',
    labels={'group_name': '', 'diff': 'Difference (Real − Stated)', 'flag': 'Status'},
)
fig.update_traces(texttemplate='%{text:+d}', textposition='outside', textfont_color=TEXT)
fig.add_vline(x=0, line_color=DARK, line_width=1.5)
fig.update_xaxes(range=[-35, 10])
fig.update_layout(**CHART, showlegend=True)
fig.show()

"""
INSIGHT: G10 stated 31, real 1 (−30 phantom). G05 stated 76, real 46 (−30).
G03 and G07 also over-reported by 12-13. These distort workload planning.
Action: Monthly reconciliation using students.csv as the single source of truth.
"""

'\nINSIGHT: G10 stated 31, real 1 (−30 phantom). G05 stated 76, real 46 (−30).\nG03 and G07 also over-reported by 12-13. These distort workload planning.\nAction: Monthly reconciliation using students.csv as the single source of truth.\n'

#### Q13 — Non-viable group and merge recommendation

In [71]:
g10_student = students[students['group_id'] == 'G10']['student_id'].values
 
if len(g10_student) > 0:
    g10_sid    = g10_student[0]
    g10_profile = cp[cp['student_id'] == g10_sid].groupby('concept_name')['score_pct'].mean()
    other_sids  = students[students['group_id'] != 'G10']['student_id'].unique()
    cp_others   = cp[cp['student_id'].isin(other_sids)]
 
    similarities = []
    for sid in cp_others['student_id'].unique():
        s_profile = cp_others[cp_others['student_id'] == sid].groupby('concept_name')['score_pct'].mean()
        common    = g10_profile.index.intersection(s_profile.index)
        if len(common) >= 3:
            diff = abs(g10_profile[common] - s_profile[common]).mean()
            similarities.append({'student_id': sid, 'avg_diff': round(diff, 1)})
 
    sim_df    = pd.DataFrame(similarities).sort_values('avg_diff')
    best_sid  = sim_df.iloc[0]['student_id']
    match_row = students_full[students_full['student_id'] == best_sid][
        ['student_id','full_name','group_name','course_name']
    ]
    print(f"G10 student: {g10_sid}")
    print(f"Closest concept-profile match:\n{match_row.to_string(index=False)}")
    print(f"Avg concept diff: {sim_df.iloc[0]['avg_diff']} pp")
"""
INSIGHT: G10 has 1 real student — completely non-viable.
Closest match by concept profile is in G09 (security-adjacent content).
Recommendation: Dissolve G10, transfer the student to G09.
"""

G10 student: S0500
Closest concept-profile match:
student_id  full_name      group_name             course_name
     S0011 Menna Saad Group 08 — C006 Machine Learning Basics
Avg concept diff: 0.6 pp

'\nINSIGHT: G10 has 1 real student — completely non-viable.\nClosest match by concept profile is in G09 (security-adjacent content).\nRecommendation: Dissolve G10, transfer the student to G09.\n'

#### Q14 — At-risk ranking: top 10 students

In [72]:
student_summary['att_score']     = (100 - student_summary['attendance_rate']) / 100
student_summary['grade_score']   = (100 - student_summary['avg_grade']) / 100
student_summary['eng_score']     = 1 - (student_summary['login_count'] / student_summary['login_count'].clip(lower=1).max())
student_summary['concept_score'] = (student_summary['failed_concept_count'] /
                                     student_summary['failed_concept_count'].clip(lower=1).max())
student_summary['risk_score'] = (
    0.35 * student_summary['att_score'] +
    0.35 * student_summary['grade_score'] +
    0.15 * student_summary['eng_score'] +
    0.15 * student_summary['concept_score']
).round(4)

top10 = student_summary.nlargest(10, 'risk_score').reset_index(drop=True)
top10.index += 1

fig = px.bar(
    top10.sort_values('risk_score', ascending=True),
    x='risk_score', y='full_name', orientation='h',
    color='group_name',
    text='risk_score',
    hover_data=['group_name', 'attendance_rate', 'avg_grade', 'failed_concept_count'],
    title='Q14 — Top 10 At-Risk Students  (coloured by group)',
    labels={'full_name': '', 'risk_score': 'Risk Score', 'group_name': 'Group'},
)
fig.update_traces(texttemplate='%{text:.3f}', textposition='outside', textfont_color=TEXT)
fig.update_xaxes(range=[0, 0.75])
fig.update_layout(**CHART)
fig.show()


"""
INSIGHT: 7 out of the 10 in Group 07 — this is not an individual problem, it's a group-level crisis.
All 10 are below 66% attendance and below 57% grade.
There is no single case that attends regularly and still appears in the list —
this confirms that attendance is the strongest signal in the risk score.

Action:
1. Contact all 10 this week in the order shown in the chart
2. Schedule Group 07 intervention — 7 out of 10 are from the same group
3. Alert Group 07 instructor today
"""

"\nINSIGHT: 7 out of the 10 in Group 07 — this is not an individual problem, it's a group-level crisis.\nAll 10 are below 66% attendance and below 57% grade.\nThere is no single case that attends regularly and still appears in the list —\nthis confirms that attendance is the strongest signal in the risk score.\n\nAction:\n1. Contact all 10 this week in the order shown in the chart\n2. Schedule Group 07 intervention — 7 out of 10 are from the same group\n3. Alert Group 07 instructor today\n"

In [73]:
top10 = student_summary.nlargest(10, 'risk_score')[
    ['full_name', 'group_name', 'attendance_rate', 
     'avg_grade', 'login_count', 'failed_concept_count', 'risk_score']
].reset_index(drop=True)

print(top10)
print("\nGroup distribution:")
print(top10['group_name'].value_counts())

       full_name       group_name  attendance_rate  avg_grade  login_count  \
0    Hassan Nasr  Group 04 — C002             46.2       55.2           18
1    Rowan ElBaz  Group 07 — C005             46.2       52.8           11
2  Hassan Refaat  Group 07 — C005             57.7       45.4           11
3   Habiba Halim  Group 07 — C005             50.0       54.2           13
4   Mona ElSayed  Group 07 — C005             61.5       41.9           14
5    Omar Shawky  Group 02 — C001             50.0       56.1           19
6    Aya Ramadan  Group 07 — C005             46.2       55.3           17
7   Marwan ElBaz  Group 07 — C005             50.0       47.7           21
8   Farida Halim  Group 07 — C005             53.8       48.9           19
9   Laila Farouk  Group 01 — C001             65.4       54.9           16

   failed_concept_count  risk_score
0                   6.0      0.5808
1                   4.0      0.5642
2                   4.0      0.5499
3                   4.0      0.5389
4                   4.0      0.5381
5                   5.0      0.5358
6                   4.0      0.5340
7                   4.0      0.5330
8                   4.0      0.5227
9                   6.0      0.5218

Group distribution:
group_name
Group 07 — C005    7
Group 04 — C002    1
Group 02 — C001    1
Group 01 — C001    1
Name: count, dtype: int64

#### Q15 — Group grade trends across the term

In [74]:
grades_full['date']  = pd.to_datetime(grades_full['date'], errors='coerce')
grades_full['month'] = grades_full['date'].dt.to_period('M').astype(str)
g_trends = (grades_full[grades_full['orphan']==False]
    .groupby(['group_name','month'])['score_pct']
    .mean().reset_index().round(1))
g_trends = g_trends[g_trends['month'].between('2025-12','2026-06')]
 
fig = px.line(g_trends, x='month', y='score_pct', color='group_name', markers=True,
              title='Group Average Grade Trend Across the Term',
              labels={'month':'Month','score_pct':'Average Score (%)','group_name':'Group'})
fig.update_layout(**CHART)
fig.show()
"""
INSIGHT: Most groups are stable. Group 07 is flat but consistently lowest (~60%).
No group trends strongly upward — curriculum may not be building progressively.
Action: Introduce scaffolded assessments that reward improvement over time.
"""

'\nINSIGHT: Most groups are stable. Group 07 is flat but consistently lowest (~60%).\nNo group trends strongly upward — curriculum may not be building progressively.\nAction: Introduce scaffolded assessments that reward improvement over time.\n'

# 5- Mongo Atlas

In [75]:
from pymongo import MongoClient
import pandas as pd
import numpy as np

MONGO_URI = "mongodb+srv://somiamoslhy_db_user:1bzHBIfg6Q5KOW9e@cluster0.dfjsase.mongodb.net/"
client = MongoClient(MONGO_URI)
db     = client["kayfa_analytics"]

def upload(collection_name, df, msg=True):
    """Drop collection and re-insert all rows."""
    col = db[collection_name]
    col.drop()
    if len(df) > 0:
        col.insert_many(df.to_dict('records'))
    if msg:
        print(f"  Uploaded {collection_name}: {len(df)} rows")


kpis = {
    "total_students"      : int(len(students)),
    "total_groups"        : int(len(groups)),
    "total_courses"       : int(len(courses)),
    "platform_attendance" : round(float(attendance_full['attended_flag'].mean() * 100), 1),
    "platform_avg_grade"  : round(float(grades_full[grades_full['orphan']==False]['score_pct'].mean()), 1),
    "total_events"        : int(len(eng_full)),
    "at_risk_count"       : int((student_summary['segment'] == 'At-Risk').sum()),
}
db["kpis"].drop()
db["kpis"].insert_one(kpis)
print("  Uploaded kpis: 1 document")


# ══════════════════════════════════════════════════════════
# 2. Group attendance summary (Q1)
# ══════════════════════════════════════════════════════════
g_att = attendance_full.copy()
g_att['attended_flag'] = (g_att['status'] == 'attended').astype(int)

group_att = (
    g_att.groupby(['group_name'])['attended_flag']
    .agg(attendance_rate='mean', total_sessions='count')
    .reset_index()
)
group_att['attendance_rate'] = (group_att['attendance_rate'] * 100).round(1)
group_att = group_att.merge(
    groups[['group_name','course_id','instructor']], on='group_name', how='left'
)
upload("group_attendance", group_att)


# ══════════════════════════════════════════════════════════
# 3. Grade summaries by course and type (Q2, Q3)
# ══════════════════════════════════════════════════════════
grades_clean = grades_full[grades_full['orphan'] == False].copy()

# by course
course_grades = (
    grades_clean.groupby('course_name')['score_pct']
    .agg(avg_grade='mean', std_grade='std', count='count')
    .reset_index().round(2)
)
upload("grade_by_course", course_grades)

# by assessment type
type_grades = (
    grades_clean.groupby('type')['score_pct']
    .agg(avg_grade='mean', std_grade='std', count='count')
    .reset_index().round(2)
)
upload("grade_by_type", type_grades)


# ══════════════════════════════════════════════════════════
# 4. Student summary table (Q4, Q5, Q10, Q11, Q14)
# ══════════════════════════════════════════════════════════
summary_cols = [
    'student_id','full_name','age','gender','city','group_id','group_name',
    'course_name','attendance_rate','avg_grade','login_count',
    'total_video_mins','failed_concept_count','segment','risk_score',
    'age_group'
]
# convert categoricals to string for MongoDB
ss_upload = student_summary[summary_cols].copy()
ss_upload['age_group'] = ss_upload['age_group'].astype(str)
ss_upload = ss_upload.fillna(0)
upload("student_summary", ss_upload)


# ══════════════════════════════════════════════════════════
# 5. Concept failure rates (Q6, Q7)
# ══════════════════════════════════════════════════════════
concept_fail = (
    cp_full.groupby(['concept_name','course_id'])['mastery_status']
    .apply(lambda x: round((x=='failed').sum() / len(x) * 100, 1))
    .reset_index()
)
concept_fail.columns = ['concept_name','course_id','fail_rate']
concept_fail = concept_fail.merge(
    courses[['course_id','course_name']], on='course_id', how='left'
)
upload("concept_failures", concept_fail)

# Recursion trend over time (Q7)
recursion = cp_full[cp_full['concept_name'] == 'Recursion'].copy()
recursion['timestamp'] = pd.to_datetime(recursion['timestamp'], errors='coerce')
recursion['month'] = recursion['timestamp'].dt.to_period('M').astype(str)
rec_trend = (
    recursion.groupby('month')
    .agg(avg_mastery=('score_pct','mean'), pass_rate=('mastery_status', lambda x: round((x=='passed').sum()/len(x)*100,1)))
    .reset_index().round(1)
)
upload("recursion_trend", rec_trend)


# ══════════════════════════════════════════════════════════
# 6. Late submission analysis (Q8)
# ══════════════════════════════════════════════════════════
subs_upload = subs_full[
    ['student_id','assessment_id','course_name','group_name',
     'is_late','hours_before_deadline','grade_score_pct','time_spent_minutes']
].dropna(subset=['grade_score_pct']).copy()
subs_upload['is_late'] = subs_upload['is_late'].astype(bool)
subs_upload['hours_before_deadline'] = subs_upload['hours_before_deadline'].fillna(0)
upload("submission_analysis", subs_upload)


# ══════════════════════════════════════════════════════════
# 7. Monthly time series — attendance + engagement (Q9)
# ══════════════════════════════════════════════════════════
att_time = attendance_full.copy()
att_time['session_datetime'] = pd.to_datetime(att_time['session_datetime'], errors='coerce')
att_time['month'] = att_time['session_datetime'].dt.to_period('M').astype(str)
att_monthly = (
    att_time[att_time['month'].between('2025-12','2026-06')]
    .groupby('month')['attended_flag']
    .mean().reset_index()
)
att_monthly['attendance_rate'] = (att_monthly['attended_flag'] * 100).round(1)

eng_monthly = (
    eng_full[eng_full['event_month'].between('2025-12','2026-06')]
    .groupby('event_month').size().reset_index(name='event_count')
    .rename(columns={'event_month':'month'})
)
time_series = att_monthly[['month','attendance_rate']].merge(
    eng_monthly, on='month', how='outer'
).sort_values('month').fillna(0)
upload("time_series", time_series)


# ══════════════════════════════════════════════════════════
# 8. Group size discrepancies (Q12)
# ══════════════════════════════════════════════════════════
real_counts = (
    students[students['group_id'].notna()]
    .groupby('group_id').size().reset_index(name='real_count')
)
q12 = groups.merge(real_counts, on='group_id', how='left').fillna(0)
q12['real_count'] = q12['real_count'].astype(int)
q12['diff'] = q12['real_count'] - q12['stated_num_students']
q12['flag'] = q12['diff'].apply(
    lambda d: 'Under-reported' if d > 5 else ('Over-reported' if d < -5 else 'Accurate')
)
upload("group_size_audit", q12[['group_id','group_name','stated_num_students','real_count','diff','flag']])


# ══════════════════════════════════════════════════════════
# 9. Top 10 at-risk students (Q14)
# ══════════════════════════════════════════════════════════
top10 = student_summary.nlargest(10, 'risk_score')[
    ['student_id','full_name','group_name','course_name',
     'attendance_rate','avg_grade','login_count',
     'failed_concept_count','risk_score']
].copy()
top10['rank'] = range(1, 11)
upload("at_risk_top10", top10)


# ══════════════════════════════════════════════════════════
# 10. Group grade trends (Q15)
# ══════════════════════════════════════════════════════════
grades_full['date']  = pd.to_datetime(grades_full['date'],  errors='coerce')
grades_full['month'] = grades_full['date'].dt.to_period('M').astype(str)
g_trends = (
    grades_full[grades_full['orphan'] == False]
    .groupby(['group_name','month'])['score_pct']
    .mean().reset_index().round(1)
)
g_trends = g_trends[g_trends['month'].between('2025-12','2026-06')]
upload("group_grade_trends", g_trends)


# ══════════════════════════════════════════════════════════
# DONE
# ══════════════════════════════════════════════════════════
print("\nAll collections uploaded to MongoDB Atlas:")
for col in db.list_collection_names():
    print(f"  {col}: {db[col].count_documents({})} documents")

client.close()

  Uploaded kpis: 1 document
  Uploaded group_attendance: 10 rows
  Uploaded grade_by_course: 7 rows
  Uploaded grade_by_type: 4 rows
  Uploaded student_summary: 500 rows
  Uploaded concept_failures: 39 rows
  Uploaded recursion_trend: 5 rows
  Uploaded submission_analysis: 4504 rows
  Uploaded time_series: 6 rows
  Uploaded group_size_audit: 10 rows
  Uploaded at_risk_top10: 10 rows
  Uploaded group_grade_trends: 60 rows

All collections uploaded to MongoDB Atlas:
  group_size_audit: 10 documents
  student_summary: 500 documents
  recursion_trend: 5 documents
  at_risk_top10: 10 documents
  kpis: 1 documents
  concept_failures: 39 documents
  time_series: 6 documents
  grades_full: 6074 documents
  group_grade_trends: 60 documents
  grade_by_type: 4 documents
  grade_by_course: 7 documents
  submission_analysis: 4504 documents
  group_attendance: 10 documents